# -*- coding: utf-8 -*-
"""01_baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYLXSOUIgzArUfucWoVs4NWU5KuJjAQe

# 초기화 셀
"""

# ============================================================
# KITTI Monocular Depth 프로젝트 초기화 셀
# ============================================================

from google.colab import drive
from pathlib import Path
from PIL import Image

import json
import tarfile
import shutil
import random
import numpy as np

import torch
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torchvision.transforms import functional as TF
from torchvision.transforms import InterpolationMode


# ============================================================
# 1. Google Drive 연결
# ============================================================
drive.mount(
    "/content/drive",
    force_remount=False,
)


# ============================================================
# 2. 프로젝트 경로 설정
# ============================================================
PROJECT_ROOT = Path(
    "/content/drive/MyDrive/2026/comento/week4"
)

DATASET_ARCHIVE_PATH = (
    PROJECT_ROOT
    / "dataset"
    / "kitti_eigen.tar"
)

SPLIT_JSON_PATH = (
    PROJECT_ROOT
    / "splits"
    / "kitti_subset_splits.json"
)

OUTPUT_DIR = PROJECT_ROOT / "outputs"
CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"
LOG_DIR = PROJECT_ROOT / "logs"

for directory in [
    OUTPUT_DIR,
    CHECKPOINT_DIR,
    LOG_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )


# ============================================================
# 3. Drive 파일 존재 여부 확인
# ============================================================
if not DATASET_ARCHIVE_PATH.exists():
    raise FileNotFoundError(
        "Drive에서 KITTI TAR 파일을 찾을 수 없습니다.\n"
        f"확인 경로: {DATASET_ARCHIVE_PATH}"
    )

if not SPLIT_JSON_PATH.exists():
    raise FileNotFoundError(
        "Drive에서 split JSON을 찾을 수 없습니다.\n"
        f"확인 경로: {SPLIT_JSON_PATH}"
    )

print("Drive 파일 확인 완료")


# ============================================================
# 4. KITTI 데이터를 Colab 로컬 디스크에 압축 해제
# ============================================================
LOCAL_DATA_ROOT = Path(
    "/content/kitti_data"
)

dataset_root = (
    LOCAL_DATA_ROOT
    / "kitti_eigen"
)

train_root = dataset_root / "train"
test_root = dataset_root / "test"

dataset_already_extracted = (
    train_root.exists()
    and test_root.exists()
)

if dataset_already_extracted:
    print(
        "로컬 KITTI 데이터가 이미 존재합니다."
    )

else:
    print(
        "Drive의 KITTI 데이터를 "
        "Colab 로컬 디스크에 복원합니다."
    )

    LOCAL_DATA_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )

    with tarfile.open(
        DATASET_ARCHIVE_PATH,
        mode="r",
    ) as tar:
        tar.extractall(
            path=LOCAL_DATA_ROOT
        )

    print("KITTI 데이터 복원 완료")

if not train_root.exists():
    raise FileNotFoundError(
        f"train 폴더 복원 실패: {train_root}"
    )

if not test_root.exists():
    raise FileNotFoundError(
        f"test 폴더 복원 실패: {test_root}"
    )

print("dataset_root:", dataset_root)


# ============================================================
# 5. Split JSON 로드
# ============================================================
with open(
    SPLIT_JSON_PATH,
    mode="r",
    encoding="utf-8",
) as file:
    split_data = json.load(file)

SEED = int(split_data["seed"])
IMAGE_SIZE = tuple(
    split_data["image_size"]
)
MAX_DEPTH = float(
    split_data["max_depth"]
)

print("\n========== 저장 설정 ==========")
print("Seed       :", SEED)
print("Image size :", IMAGE_SIZE)
print("Max depth  :", MAX_DEPTH)


# ============================================================
# 6. 랜덤 시드 고정
# ============================================================
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)


# ============================================================
# 7. 저장된 상대 경로 복원 함수
# ============================================================
def resolve_saved_path(
    saved_path,
    current_dataset_root,
):
    """
    JSON에 저장된 경로를 현재 dataset_root 기준으로 복원합니다.

    상대 경로인 경우:
        dataset_root / saved_path

    과거 절대 경로인 경우:
        경로 안의 train 또는 test 이후 부분을 사용
    """
    saved_path = Path(saved_path)

    # 일반적으로 JSON에는 상대 경로가 저장되어 있음
    if not saved_path.is_absolute():
        return (
            current_dataset_root
            / saved_path
        )

    # 절대 경로로 저장된 경우 train/test부터 추출
    path_parts = saved_path.parts

    for split_name in ["train", "test"]:
        if split_name in path_parts:
            split_index = path_parts.index(
                split_name
            )

            relative_path = Path(
                *path_parts[split_index:]
            )

            return (
                current_dataset_root
                / relative_path
            )

    raise ValueError(
        "저장된 경로에서 train/test를 "
        f"찾을 수 없습니다: {saved_path}"
    )


def restore_pairs(
    saved_pairs,
    current_dataset_root,
):
    restored_pairs = []

    for item in saved_pairs:
        restored_item = {
            "rgb": resolve_saved_path(
                item["rgb"],
                current_dataset_root,
            ),
            "depth": resolve_saved_path(
                item["depth"],
                current_dataset_root,
            ),
            "sequence": item.get(
                "sequence",
                "",
            ),
            "frame": item.get(
                "frame",
                "",
            ),
        }

        restored_pairs.append(
            restored_item
        )

    return restored_pairs


train_subset_pairs = restore_pairs(
    split_data["train"],
    dataset_root,
)

val_subset_pairs = restore_pairs(
    split_data["val"],
    dataset_root,
)

test_subset_pairs = restore_pairs(
    split_data["test"],
    dataset_root,
)

print("\n========== Pair 복원 ==========")
print("Train :", len(train_subset_pairs))
print("Val   :", len(val_subset_pairs))
print("Test  :", len(test_subset_pairs))


# ============================================================
# 8. 파일 경로 검증
# ============================================================
def validate_pair_paths(
    pairs,
    split_name,
):
    missing_rgb = []
    missing_depth = []

    for pair in pairs:
        if not pair["rgb"].exists():
            missing_rgb.append(
                str(pair["rgb"])
            )

        if not pair["depth"].exists():
            missing_depth.append(
                str(pair["depth"])
            )

    if missing_rgb or missing_depth:
        raise FileNotFoundError(
            f"{split_name} 경로 복원 실패\n"
            f"누락 RGB: {len(missing_rgb)}\n"
            f"누락 Depth: {len(missing_depth)}"
        )

    print(
        f"{split_name}: 모든 경로 정상"
    )


validate_pair_paths(
    train_subset_pairs,
    "Train",
)

validate_pair_paths(
    val_subset_pairs,
    "Validation",
)

validate_pair_paths(
    test_subset_pairs,
    "Test",
)


# ============================================================
# 9. PyTorch Dataset 정의
# ============================================================
class KITTIDepthDataset(Dataset):
    def __init__(
        self,
        pairs,
        image_size=(518, 518),
        max_depth=80.0,
    ):
        self.pairs = pairs
        self.image_size = tuple(
            image_size
        )
        self.max_depth = float(
            max_depth
        )

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, index):
        pair = self.pairs[index]

        rgb_path = Path(pair["rgb"])
        depth_path = Path(pair["depth"])

        # --------------------------------------------
        # RGB 이미지 로드
        # --------------------------------------------
        with Image.open(rgb_path) as image:
            image = image.convert("RGB")

            image = TF.resize(
                image,
                size=list(self.image_size),
                interpolation=(
                    InterpolationMode.BILINEAR
                ),
                antialias=True,
            )

            image_tensor = TF.to_tensor(
                image
            )

        # --------------------------------------------
        # KITTI Depth 로드
        # uint16 값 / 256 = meter
        # --------------------------------------------
        with Image.open(depth_path) as depth_image:
            depth_raw = np.array(
                depth_image,
                dtype=np.uint16,
            )

        depth_m = (
            depth_raw.astype(np.float32)
            / 256.0
        )

        valid_mask = (
            (depth_m > 0.0)
            & (depth_m <= self.max_depth)
            & np.isfinite(depth_m)
        )

        depth_tensor = torch.from_numpy(
            depth_m
        ).unsqueeze(0)

        mask_tensor = torch.from_numpy(
            valid_mask.astype(np.float32)
        ).unsqueeze(0)

        # --------------------------------------------
        # Depth / mask resize
        # [1,H,W] → [1,1,H,W] → resize
        # --------------------------------------------
        depth_tensor = F.interpolate(
            depth_tensor.unsqueeze(0),
            size=self.image_size,
            mode="nearest",
        ).squeeze(0)

        mask_tensor = F.interpolate(
            mask_tensor.unsqueeze(0),
            size=self.image_size,
            mode="nearest",
        ).squeeze(0).bool()

        # 유효하지 않은 depth 값은 0으로 정리
        depth_tensor = torch.where(
            mask_tensor,
            depth_tensor,
            torch.zeros_like(
                depth_tensor
            ),
        )

        return {
            "image": image_tensor,
            "depth": depth_tensor,
            "valid_mask": mask_tensor,
            "rgb_path": str(rgb_path),
            "depth_path": str(depth_path),
            "sequence": pair["sequence"],
            "frame": pair["frame"],
        }


# ============================================================
# 10. Dataset 객체 생성
# ============================================================
train_dataset = KITTIDepthDataset(
    train_subset_pairs,
    image_size=IMAGE_SIZE,
    max_depth=MAX_DEPTH,
)

val_dataset = KITTIDepthDataset(
    val_subset_pairs,
    image_size=IMAGE_SIZE,
    max_depth=MAX_DEPTH,
)

test_dataset = KITTIDepthDataset(
    test_subset_pairs,
    image_size=IMAGE_SIZE,
    max_depth=MAX_DEPTH,
)

print("\n========== Dataset ==========")
print("Train :", len(train_dataset))
print("Val   :", len(val_dataset))
print("Test  :", len(test_dataset))


# ============================================================
# 11. DataLoader 생성
# ============================================================
BATCH_SIZE = 2
NUM_WORKERS = 2

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    persistent_workers=(
        NUM_WORKERS > 0
    ),
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    persistent_workers=(
        NUM_WORKERS > 0
    ),
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    persistent_workers=(
        NUM_WORKERS > 0
    ),
)


# ============================================================
# 12. Batch 검증
# ============================================================
batch = next(
    iter(train_loader)
)

print("\n========== Batch 검증 ==========")
print(
    "Image shape:",
    batch["image"].shape,
)
print(
    "Depth shape:",
    batch["depth"].shape,
)
print(
    "Mask shape :",
    batch["valid_mask"].shape,
)

print(
    "Image dtype:",
    batch["image"].dtype,
)
print(
    "Depth dtype:",
    batch["depth"].dtype,
)
print(
    "Mask dtype :",
    batch["valid_mask"].dtype,
)

print(
    "Valid ratio:",
    batch["valid_mask"]
    .float()
    .mean()
    .item(),
)

print("\n프로젝트 초기화 완료!")

"""# Depth Anything V2 추론"""

# GPU 및 라이브러리 환경 확인

import sys
import torch
import transformers
import numpy as np
import torch.nn.functional as F
import matplotlib.pyplot as plt
import pandas as pd
import random
import math

from pathlib import Path
from PIL import Image

from google.colab import drive
from pathlib import Path
from PIL import Image

print("Python version       :", sys.version)
print("PyTorch version      :", torch.__version__)
print("Transformers version :", transformers.__version__)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device               :", device)

if torch.cuda.is_available():
    print("GPU name             :", torch.cuda.get_device_name(0))
    print(
        "GPU memory           :",
        round(
            torch.cuda.get_device_properties(0).total_memory
            / (1024 ** 3),
            2,
        ),
        "GB",
    )

# 필요한 라이브러리 설치
!pip install -q --upgrade transformers accelerate safetensors

import transformers

from transformers import (
    AutoImageProcessor,
    AutoModelForDepthEstimation,
)

print(
    "Transformers version:",
    transformers.__version__,
)

# 모델 종류 결정
MODEL_NAME = (
    "depth-anything/"
    "Depth-Anything-V2-Small-hf"
)

# Image Processor와 모델 로드

MODEL_NAME = (
    "depth-anything/"
    "Depth-Anything-V2-Small-hf"
)

print("모델을 불러오는 중입니다.")
print("Model:", MODEL_NAME)

image_processor = (
    AutoImageProcessor.from_pretrained(
        MODEL_NAME
    )
)

model = (
    AutoModelForDepthEstimation.from_pretrained(
        MODEL_NAME
    )
)

model = model.to(device)
model.eval()

print("\n모델 로드 완료")
print("Model class :", model.__class__.__name__)
print("Device      :", next(model.parameters()).device)

parameter_count = sum(
    parameter.numel()
    for parameter in model.parameters()
)

print(
    "Parameters  :",
    f"{parameter_count:,}",
)

# Test 이미지 한 장 불러오기

sample_pair = test_subset_pairs[0]

rgb_path = Path(sample_pair["rgb"])
depth_path = Path(sample_pair["depth"])

# RGB 원본 이미지
rgb_image = Image.open(
    rgb_path
).convert("RGB")

# KITTI Ground Truth depth
depth_raw = np.array(
    Image.open(depth_path),
    dtype=np.uint16,
)

depth_gt = (
    depth_raw.astype(np.float32)
    / 256.0
)

valid_mask = (
    (depth_gt > 0.0)
    & (depth_gt <= MAX_DEPTH)
    & np.isfinite(depth_gt)
)

print("RGB size        :", rgb_image.size)
print("GT depth shape  :", depth_gt.shape)
print("GT depth dtype  :", depth_gt.dtype)
print("Valid pixel rate:", valid_mask.mean())

if valid_mask.any():
    print(
        "Valid min depth :",
        depth_gt[valid_mask].min(),
    )
    print(
        "Valid max depth :",
        depth_gt[valid_mask].max(),
    )

# 모델 입력 전처리
inputs = image_processor(
    images=rgb_image,
    return_tensors="pt",
)

print("Processor output keys:")
print(inputs.keys())

for key, value in inputs.items():
    print(
        key,
        value.shape,
        value.dtype,
    )

# 입력을 GPU 이동
inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

print(
    "Input device:",
    inputs["pixel_values"].device,
)

# Depth Anything V2 추론
with torch.inference_mode():
    outputs = model(**inputs)

predicted_depth = outputs.predicted_depth

print(
    "Raw prediction shape:",
    predicted_depth.shape,
)

print(
    "Raw prediction dtype:",
    predicted_depth.dtype,
)

print(
    "Raw prediction device:",
    predicted_depth.device,
)

# 예상 결과 : torch.Size([1, H, W])

# 예측값을 원본 KITTI 크기로 복원
# 모델 출력 크기는 원본 RGB 크기와 다를 수 있으므로 원본 크기로 보간

original_width, original_height = rgb_image.size

prediction_resized = F.interpolate(
    predicted_depth.unsqueeze(1),
    size=(
        original_height,
        original_width,
    ),
    mode="bicubic",
    align_corners=False,
)

prediction_resized = (
    prediction_resized
    .squeeze(0)
    .squeeze(0)
    .detach()
    .cpu()
    .numpy()
)

print(
    "Resized prediction shape:",
    prediction_resized.shape,
)

print(
    "Prediction dtype:",
    prediction_resized.dtype,
)

print(
    "Prediction min:",
    prediction_resized.min(),
)

print(
    "Prediction max:",
    prediction_resized.max(),
)

print(
    "Finite values:",
    np.isfinite(
        prediction_resized
    ).all(),
)

# 결과 예상
# Resized prediction shape: (원본 높이, 원본 너비)
# Prediction dtype         : float32
# Finite values            : True

"""주의할 점
여기서 Ground Truth와 Prediction의 색이 같은 의미를 갖지는 않음!

- Ground Truth colorbar: 미터 단위
- Prediction colorbar: 상대적인 모델 출력값

따라서 현재는 색상값 자체보다 다음 구조를 확인

- 도로 영역이 연속적으로 표현되는지
- 가까운 차량과 먼 배경이 구분되는지
- 건물, 차량, 하늘 경계가 드러나는지
- 결과 전체가 단색처럼 나오지 않는지
"""

# RGB*Ground Trugh/Prediction 시각화
# 유효하지 않은 GT 영역은 시각화에서 가림
depth_gt_masked = np.ma.masked_where(
    ~valid_mask,
    depth_gt,
)

fig, axes = plt.subplots(
    1,
    3,
    figsize=(18, 5),
)

# ------------------------------------------------------------
# RGB
# ------------------------------------------------------------
axes[0].imshow(rgb_image)
axes[0].set_title("RGB Image")
axes[0].axis("off")

# ------------------------------------------------------------
# Ground Truth metric depth
# ------------------------------------------------------------
gt_plot = axes[1].imshow(
    depth_gt_masked,
    cmap="turbo",
    vmin=0,
    vmax=MAX_DEPTH,
)

axes[1].set_title(
    "KITTI Ground Truth Depth (m)"
)
axes[1].axis("off")

fig.colorbar(
    gt_plot,
    ax=axes[1],
    fraction=0.046,
    pad=0.04,
)

# ------------------------------------------------------------
# Depth Anything V2 relative prediction
# ------------------------------------------------------------
pred_plot = axes[2].imshow(
    prediction_resized,
    cmap="turbo",
)

axes[2].set_title(
    "Depth Anything V2 Prediction\n(Relative Depth)"
)
axes[2].axis("off")

fig.colorbar(
    pred_plot,
    ax=axes[2],
    fraction=0.046,
    pad=0.04,
)

plt.tight_layout()
plt.show()

# 추론 성공 여부 자동 확인
assert (
    prediction_resized.shape
    == depth_gt.shape
), (
    "Prediction과 Ground Truth의 "
    "해상도가 다릅니다."
)

assert np.isfinite(
    prediction_resized
).all(), (
    "Prediction에 NaN 또는 Inf가 있습니다."
)

assert (
    prediction_resized.max()
    > prediction_resized.min()
), (
    "Prediction이 단일 값으로만 "
    "구성되어 있습니다."
)

print("✅ Depth Anything V2 단일 이미지 추론 성공")
print(
    "RGB shape       :",
    np.asarray(rgb_image).shape,
)
print(
    "GT depth shape  :",
    depth_gt.shape,
)
print(
    "Prediction shape:",
    prediction_resized.shape,
)

# 단일 이미지 추론 함수

def predict_relative_depth(
    rgb_input,
    model,
    image_processor,
    device,
):
    """
    Depth Anything V2 relative depth 추론 함수

    Parameters
    ----------
    rgb_input:
        PIL.Image 또는 이미지 파일 경로

    model:
        AutoModelForDepthEstimation 모델

    image_processor:
        AutoImageProcessor 객체

    device:
        torch.device("cuda") 또는 torch.device("cpu")

    Returns
    -------
    result: dict
        {
            "rgb_image": 원본 PIL 이미지,
            "predicted_depth": 원본 크기로 복원된 numpy 배열,
            "raw_prediction_shape": 모델 원본 출력 크기,
            "original_size": (width, height)
        }
    """

    # --------------------------------------------------------
    # 1. RGB 이미지 준비
    # --------------------------------------------------------
    if isinstance(rgb_input, (str, Path)):
        rgb_path = Path(rgb_input)

        if not rgb_path.exists():
            raise FileNotFoundError(
                f"RGB 이미지를 찾을 수 없습니다: {rgb_path}"
            )

        with Image.open(rgb_path) as image:
            rgb_image = image.convert("RGB")

    elif isinstance(rgb_input, Image.Image):
        rgb_image = rgb_input.convert("RGB")

    else:
        raise TypeError(
            "rgb_input은 파일 경로 또는 PIL.Image여야 합니다."
        )

    original_width, original_height = rgb_image.size

    # --------------------------------------------------------
    # 2. 모델 입력 전처리
    # --------------------------------------------------------
    inputs = image_processor(
        images=rgb_image,
        return_tensors="pt",
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # --------------------------------------------------------
    # 3. 모델 추론
    # --------------------------------------------------------
    model.eval()

    with torch.inference_mode():
        outputs = model(**inputs)

    predicted_depth = outputs.predicted_depth

    raw_prediction_shape = tuple(
        predicted_depth.shape
    )

    # --------------------------------------------------------
    # 4. 원본 이미지 크기로 복원
    # --------------------------------------------------------
    prediction_resized = F.interpolate(
        predicted_depth.unsqueeze(1),
        size=(
            original_height,
            original_width,
        ),
        mode="bicubic",
        align_corners=False,
    )

    prediction_resized = (
        prediction_resized
        .squeeze(0)
        .squeeze(0)
        .detach()
        .cpu()
        .numpy()
        .astype(np.float32)
    )

    # --------------------------------------------------------
    # 5. 결과 검증
    # --------------------------------------------------------
    if prediction_resized.shape != (
        original_height,
        original_width,
    ):
        raise ValueError(
            "예측 결과가 원본 이미지 크기와 일치하지 않습니다."
        )

    if not np.isfinite(prediction_resized).all():
        raise ValueError(
            "예측 결과에 NaN 또는 Inf가 포함되어 있습니다."
        )

    if (
        prediction_resized.max()
        <= prediction_resized.min()
    ):
        raise ValueError(
            "예측 결과가 단일 값으로 구성되어 있습니다."
        )

    return {
        "rgb_image": rgb_image,
        "predicted_depth": prediction_resized,
        "raw_prediction_shape": raw_prediction_shape,
        "original_size": (
            original_width,
            original_height,
        ),
    }

# 사용한 test 이미지에 함수 적용
sample_pair = test_subset_pairs[0]

result = predict_relative_depth(
    rgb_input=sample_pair["rgb"],
    model=model,
    image_processor=image_processor,
    device=device,
)

predicted_depth = result["predicted_depth"]

print("Original size       :", result["original_size"])
print("Raw prediction shape:", result["raw_prediction_shape"])
print("Final depth shape   :", predicted_depth.shape)
print("Prediction min      :", predicted_depth.min())
print("Prediction max      :", predicted_depth.max())
print("Finite values       :", np.isfinite(predicted_depth).all())

# 예상 결과
# Original size       : (1242, 375)
# Raw prediction shape: (1, 518, 1722)
# Final depth shape   : (375, 1242)
# Prediction min      : 약 -0.16
# Prediction max      : 약 7.76
# Finite values       : True

# Ground Truth까지 함께 불러오는 함수
def load_kitti_sample(pair, max_depth=80.0):
    """
    KITTI RGB 및 Ground Truth depth를 불러옵니다.
    """

    rgb_path = Path(pair["rgb"])
    depth_path = Path(pair["depth"])

    if not rgb_path.exists():
        raise FileNotFoundError(
            f"RGB 파일이 없습니다: {rgb_path}"
        )

    if not depth_path.exists():
        raise FileNotFoundError(
            f"Depth 파일이 없습니다: {depth_path}"
        )

    with Image.open(rgb_path) as image:
        rgb_image = image.convert("RGB")

    with Image.open(depth_path) as depth_image:
        depth_raw = np.array(
            depth_image,
            dtype=np.uint16,
        )

    depth_gt = (
        depth_raw.astype(np.float32)
        / 256.0
    )

    valid_mask = (
        (depth_gt > 0.0)
        & (depth_gt <= max_depth)
        & np.isfinite(depth_gt)
    )

    return {
        "rgb_image": rgb_image,
        "depth_gt": depth_gt,
        "valid_mask": valid_mask,
        "rgb_path": rgb_path,
        "depth_path": depth_path,
        "sequence": pair.get("sequence", ""),
        "frame": pair.get("frame", ""),
    }

# 추론과 시각화 연결

def visualize_relative_depth_result(
    pair,
    model,
    image_processor,
    device,
    max_depth=80.0,
):
    """
    RGB, KITTI Ground Truth, relative prediction을 시각화합니다.
    """

    sample = load_kitti_sample(
        pair,
        max_depth=max_depth,
    )

    prediction_result = predict_relative_depth(
        rgb_input=sample["rgb_image"],
        model=model,
        image_processor=image_processor,
        device=device,
    )

    rgb_image = sample["rgb_image"]
    depth_gt = sample["depth_gt"]
    valid_mask = sample["valid_mask"]

    predicted_depth = prediction_result[
        "predicted_depth"
    ]

    depth_gt_masked = np.ma.masked_where(
        ~valid_mask,
        depth_gt,
    )

    prediction_visual = np.clip(
        predicted_depth,
        a_min=0.0,
        a_max=None,
    )

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(18, 5),
    )

    axes[0].imshow(rgb_image)
    axes[0].set_title("RGB Image")
    axes[0].axis("off")

    gt_plot = axes[1].imshow(
        depth_gt_masked,
        cmap="turbo",
        vmin=0,
        vmax=max_depth,
    )

    axes[1].set_title(
        "KITTI Ground Truth Depth (m)"
    )
    axes[1].axis("off")

    fig.colorbar(
        gt_plot,
        ax=axes[1],
        fraction=0.046,
        pad=0.04,
    )

    pred_plot = axes[2].imshow(
        prediction_visual,
        cmap="turbo",
    )

    axes[2].set_title(
        "Depth Anything V2\nRelative Prediction"
    )
    axes[2].axis("off")

    fig.colorbar(
        pred_plot,
        ax=axes[2],
        fraction=0.046,
        pad=0.04,
    )

    plt.tight_layout()
    plt.show()

    print("Sequence           :", sample["sequence"])
    print("Frame              :", sample["frame"])
    print("GT valid pixel rate:", valid_mask.mean())
    print(
        "Prediction range   :",
        predicted_depth.min(),
        "~",
        predicted_depth.max(),
    )

    return {
        **sample,
        **prediction_result,
    }

# 함수 실행
visualization_result = (
    visualize_relative_depth_result(
        pair=test_subset_pairs[0],
        model=model,
        image_processor=image_processor,
        device=device,
        max_depth=MAX_DEPTH,
    )
)

# 다른 이미지에서도 확인 : test suset의 다른 이미지에도 적용
visualization_result_2 = (
    visualize_relative_depth_result(
        pair=test_subset_pairs[10],
        model=model,
        image_processor=image_processor,
        device=device,
        max_depth=MAX_DEPTH,
    )
)

"""# Relative Baseline 결과 생성 및 저장"""

# Baseline 저장 폴더와 샘플 선정

# ============================================================
# 1. Baseline 결과 저장 경로
# ============================================================
BASELINE_ROOT = (
    PROJECT_ROOT
    / "outputs"
    / "relative_baseline"
)

PREDICTION_DIR = BASELINE_ROOT / "predictions"
VISUALIZATION_DIR = BASELINE_ROOT / "visualizations"

PREDICTION_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

VISUALIZATION_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

# ============================================================
# 2. 고정 샘플 번호
# ============================================================
BASELINE_INDICES = [
    0,
    10,
    20,
    30,
    40,
    50,
    60,
    70,
    80,
    90,
]

# test subset 크기를 넘는 번호 제거
BASELINE_INDICES = [
    index
    for index in BASELINE_INDICES
    if index < len(test_subset_pairs)
]

# 재현을 위해 선택된 번호 저장
INDEX_JSON_PATH = (
    BASELINE_ROOT
    / "baseline_indices.json"
)

with open(
    INDEX_JSON_PATH,
    mode="w",
    encoding="utf-8",
) as file:
    json.dump(
        {
            "model_name": MODEL_NAME,
            "indices": BASELINE_INDICES,
            "prediction_type": "relative_depth",
        },
        file,
        ensure_ascii=False,
        indent=2,
    )

print("Baseline root :", BASELINE_ROOT)
print("Sample indices:", BASELINE_INDICES)
print("Sample count  :", len(BASELINE_INDICES))

# 테스트 subset 100장이면 총 10장 선택

"""Relative prediction은 이미지마다 출력 범위가 달라질 수 있으므로, PNG 저장용으로만 0~1 범위로 정규화

극단값의 영향을 줄이기 위해 최소·최댓값 대신 2%와 98% 분위수를 사용
"""

# 시각화용 정규화 함수
def normalize_relative_depth_for_visualization(
    depth,
    lower_percentile=2.0,
    upper_percentile=98.0,
):
    """
    Relative depth를 시각화용 0~1 범위로 정규화합니다.

    주의:
    이 결과는 시각화 전용입니다.
    모델의 원본 prediction은 변경하지 않습니다.
    """

    depth = np.asarray(
        depth,
        dtype=np.float32,
    )

    finite_mask = np.isfinite(depth)

    if not finite_mask.any():
        raise ValueError(
            "유한한 depth 값이 없습니다."
        )

    valid_values = depth[finite_mask]

    lower_value = np.percentile(
        valid_values,
        lower_percentile,
    )

    upper_value = np.percentile(
        valid_values,
        upper_percentile,
    )

    if upper_value <= lower_value:
        raise ValueError(
            "Depth 정규화 범위가 올바르지 않습니다."
        )

    normalized = (
        depth - lower_value
    ) / (
        upper_value - lower_value
    )

    normalized = np.clip(
        normalized,
        0.0,
        1.0,
    )

    return normalized.astype(np.float32)

# 정규화 결과에서 0.2와 0.8이 실제 거리나 이미지 간 공통 척도 의미 X
# 각 이미지 내부 구조 보기 위한 색상 범위 조정

# 한 샘플의 Baseline 결과 저장 함수

def save_relative_baseline_sample(
    pair,
    sample_index,
    model,
    image_processor,
    device,
    prediction_dir,
    visualization_dir,
    max_depth=80.0,
):
    """
    한 KITTI 샘플의 relative depth baseline을 저장합니다.
    """

    # ========================================================
    # 1. RGB 및 KITTI GT 로드
    # ========================================================
    sample = load_kitti_sample(
        pair=pair,
        max_depth=max_depth,
    )

    # ========================================================
    # 2. Relative depth 추론
    # ========================================================
    prediction_result = predict_relative_depth(
        rgb_input=sample["rgb_image"],
        model=model,
        image_processor=image_processor,
        device=device,
    )

    predicted_depth = prediction_result[
        "predicted_depth"
    ]

    # ========================================================
    # 3. 원본 예측값 저장
    # ========================================================
    sample_name = f"sample_{sample_index:03d}"

    prediction_path = (
        prediction_dir
        / f"{sample_name}_pred_relative.npy"
    )

    np.save(
        prediction_path,
        predicted_depth.astype(np.float32),
    )

    # ========================================================
    # 4. 시각화용 배열 준비
    # ========================================================
    depth_gt_masked = np.ma.masked_where(
        ~sample["valid_mask"],
        sample["depth_gt"],
    )

    prediction_visual = (
        normalize_relative_depth_for_visualization(
            predicted_depth
        )
    )

    # ========================================================
    # 5. 비교 이미지 저장
    # ========================================================
    visualization_path = (
        visualization_dir
        / f"{sample_name}_comparison.png"
    )

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(18, 5),
    )

    axes[0].imshow(
        sample["rgb_image"]
    )
    axes[0].set_title(
        f"RGB\nTest index: {sample_index}"
    )
    axes[0].axis("off")

    gt_plot = axes[1].imshow(
        depth_gt_masked,
        cmap="turbo",
        vmin=0,
        vmax=max_depth,
    )

    axes[1].set_title(
        "KITTI Ground Truth (m)"
    )
    axes[1].axis("off")

    fig.colorbar(
        gt_plot,
        ax=axes[1],
        fraction=0.046,
        pad=0.04,
    )

    pred_plot = axes[2].imshow(
        prediction_visual,
        cmap="turbo",
        vmin=0,
        vmax=1,
    )

    axes[2].set_title(
        "Depth Anything V2\n"
        "Relative Depth (visualized)"
    )
    axes[2].axis("off")

    fig.colorbar(
        pred_plot,
        ax=axes[2],
        fraction=0.046,
        pad=0.04,
    )

    plt.tight_layout()

    fig.savefig(
        visualization_path,
        dpi=150,
        bbox_inches="tight",
    )

    plt.close(fig)

    # ========================================================
    # 6. 메타데이터 반환
    # ========================================================
    metadata = {
        "sample_index": sample_index,
        "sequence": sample["sequence"],
        "frame": sample["frame"],
        "rgb_path": str(sample["rgb_path"]),
        "depth_path": str(sample["depth_path"]),
        "prediction_path": str(prediction_path),
        "visualization_path": str(
            visualization_path
        ),
        "image_width": sample[
            "rgb_image"
        ].size[0],
        "image_height": sample[
            "rgb_image"
        ].size[1],
        "valid_pixel_rate": float(
            sample["valid_mask"].mean()
        ),
        "gt_min_depth": float(
            sample["depth_gt"][
                sample["valid_mask"]
            ].min()
        ),
        "gt_max_depth": float(
            sample["depth_gt"][
                sample["valid_mask"]
            ].max()
        ),
        "prediction_min": float(
            predicted_depth.min()
        ),
        "prediction_max": float(
            predicted_depth.max()
        ),
        "prediction_mean": float(
            predicted_depth.mean()
        ),
        "raw_prediction_shape": str(
            prediction_result[
                "raw_prediction_shape"
            ]
        ),
    }

    return metadata

# 선택한 10장의 subset 추론 및 저장

baseline_records = []

print(
    f"총 {len(BASELINE_INDICES)}개 "
    "샘플의 baseline 추론을 시작합니다.\n"
)

for order, sample_index in enumerate(
    BASELINE_INDICES,
    start=1,
):
    print(
        f"[{order:02d}/{len(BASELINE_INDICES):02d}] "
        f"Test index {sample_index} 처리 중..."
    )

    pair = test_subset_pairs[
        sample_index
    ]

    metadata = save_relative_baseline_sample(
        pair=pair,
        sample_index=sample_index,
        model=model,
        image_processor=image_processor,
        device=device,
        prediction_dir=PREDICTION_DIR,
        visualization_dir=VISUALIZATION_DIR,
        max_depth=MAX_DEPTH,
    )

    baseline_records.append(
        metadata
    )

    print(
        "  Prediction range:",
        f"{metadata['prediction_min']:.4f}",
        "~",
        f"{metadata['prediction_max']:.4f}",
    )

# GPU cache 정리
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# ============================================================
# 메타데이터 CSV 저장
# ============================================================
baseline_df = pd.DataFrame(
    baseline_records
)

BASELINE_CSV_PATH = (
    BASELINE_ROOT
    / "relative_baseline_metadata.csv"
)

baseline_df.to_csv(
    BASELINE_CSV_PATH,
    index=False,
    encoding="utf-8-sig",
)

print("\nBaseline 추론 완료")
print("Metadata CSV:", BASELINE_CSV_PATH)

display(
    baseline_df[
        [
            "sample_index",
            "sequence",
            "frame",
            "valid_pixel_rate",
            "prediction_min",
            "prediction_max",
        ]
    ]
)

# prediction과 GT의 RMSE나 MAE를 계산X
# prediction = 상대 단위 , GT = 미터 단위 이기 때문

# 상대 경로 열 추가
# 현재 RGB와 GT 경로가 /content/로 저장되어 있음
# csv를 더 독립적이고 이식 가능하게 만들기 위한 단계

baseline_df = pd.read_csv(
    BASELINE_CSV_PATH
)

def make_dataset_relative_path(path_string):
    path = Path(path_string)
    parts = path.parts

    for split_name in ["train", "test"]:
        if split_name in parts:
            split_index = parts.index(split_name)
            return str(
                Path(*parts[split_index:])
            )

    return path_string


baseline_df["rgb_relative_path"] = (
    baseline_df["rgb_path"].apply(
        make_dataset_relative_path
    )
)

baseline_df["depth_relative_path"] = (
    baseline_df["depth_path"].apply(
        make_dataset_relative_path
    )
)

baseline_df.to_csv(
    BASELINE_CSV_PATH,
    index=False,
    encoding="utf-8-sig",
)

print("상대 경로 열 추가 완료")

display(
    baseline_df[
        [
            "sample_index",
            "rgb_relative_path",
            "depth_relative_path",
        ]
    ].head()
)

# 저장된 파일 확인
saved_prediction_files = sorted(
    PREDICTION_DIR.glob(
        "*_pred_relative.npy"
    )
)

saved_visualization_files = sorted(
    VISUALIZATION_DIR.glob(
        "*_comparison.png"
    )
)

print(
    "저장된 prediction 수    :",
    len(saved_prediction_files),
)

print(
    "저장된 visualization 수 :",
    len(saved_visualization_files),
)

print(
    "Metadata CSV 존재       :",
    BASELINE_CSV_PATH.exists(),
)

if (
    len(saved_prediction_files)
    != len(BASELINE_INDICES)
):
    raise ValueError(
        "예측 파일 수가 샘플 수와 다릅니다."
    )

if (
    len(saved_visualization_files)
    != len(BASELINE_INDICES)
):
    raise ValueError(
        "시각화 파일 수가 샘플 수와 다릅니다."
    )

print(
    "\n✅ 모든 baseline 결과가 "
    "정상적으로 저장되었습니다."
)

# # 저장된 결과 일부 다시 열어보기
# preview_path = (
#     VISUALIZATION_DIR
#     / "sample_000_comparison.png"
# )

# if not preview_path.exists():
#     preview_path = (
#         saved_visualization_files[0]
#     )

# with Image.open(
#     preview_path
# ) as preview_image:
#     plt.figure(
#         figsize=(18, 5)
#     )
#     plt.imshow(preview_image)
#     plt.axis("off")
#     plt.title(
#         preview_path.name
#     )
#     plt.show()

# 여러 결과를 한 화면에서 비교
# 10장의 prediction만 빠르게 확인하는 요약 그림

sample_count = len(
    BASELINE_INDICES
)

column_count = 2
row_count = math.ceil(
    sample_count / column_count
)

fig, axes = plt.subplots(
    row_count,
    column_count,
    figsize=(
        16,
        row_count * 4,
    ),
)

axes = np.asarray(
    axes
).reshape(-1)

for axis, sample_index in zip(
    axes,
    BASELINE_INDICES,
):
    pair = test_subset_pairs[
        sample_index
    ]

    sample = load_kitti_sample(
        pair,
        max_depth=MAX_DEPTH,
    )

    prediction_path = (
        PREDICTION_DIR
        / (
            f"sample_{sample_index:03d}"
            "_pred_relative.npy"
        )
    )

    predicted_depth = np.load(
        prediction_path
    )

    prediction_visual = (
        normalize_relative_depth_for_visualization(
            predicted_depth
        )
    )

    # RGB와 prediction을 좌우로 결합
    rgb_array = np.asarray(
        sample["rgb_image"]
    )

    prediction_rgb = plt.get_cmap(
        "turbo"
    )(
        prediction_visual
    )[:, :, :3]

    prediction_rgb = (
        prediction_rgb * 255
    ).astype(np.uint8)

    comparison = np.concatenate(
        [
            rgb_array,
            prediction_rgb,
        ],
        axis=1,
    )

    axis.imshow(comparison)
    axis.set_title(
        f"Test index {sample_index}\n"
        "RGB | Relative depth"
    )
    axis.axis("off")

# 남는 축 숨기기
for axis in axes[sample_count:]:
    axis.axis("off")

plt.tight_layout()

SUMMARY_PATH = (
    BASELINE_ROOT
    / "relative_baseline_summary.png"
)

fig.savefig(
    SUMMARY_PATH,
    dpi=150,
    bbox_inches="tight",
)

plt.show()
plt.close(fig)

print("Summary 저장 위치:", SUMMARY_PATH)

"""# Metric Outdoor Baseline 평가

출력값이 미터 단위인 체크포인트를 사용

: GT와 비교하여 '평가'를 하기 위함
"""

# Metric 모델 불러오기
# 기존 relative 모델 변수와 구분


METRIC_MODEL_NAME = (
    "depth-anything/"
    "Depth-Anything-V2-Metric-Outdoor-Small-hf"
)

metric_image_processor = (
    AutoImageProcessor.from_pretrained(
        METRIC_MODEL_NAME
    )
)

metric_model = (
    AutoModelForDepthEstimation.from_pretrained(
        METRIC_MODEL_NAME
    )
)

metric_model = metric_model.to(device)
metric_model.eval()

print("Metric model :", METRIC_MODEL_NAME)
print("Device       :", device)
print(
    "Model max depth:",
    getattr(
        metric_model.config,
        "max_depth",
        "설정 없음",
    ),
)

# Metric depth 추론 함수
# relative 추론 함수와 다른 점 : "미터" 단위로 취급

def predict_metric_depth(
    rgb_input,
    model,
    image_processor,
    device,
    min_depth=1e-3,
    max_depth=80.0,
):
    """
    Depth Anything V2 Metric Outdoor 추론 함수

    Parameters
    ----------
    rgb_input:
        이미지 경로 또는 PIL.Image

    model:
        Metric Depth Anything V2 모델

    image_processor:
        Metric 모델용 AutoImageProcessor

    device:
        torch.device

    min_depth:
        출력 깊이의 최소 허용값

    max_depth:
        출력 깊이의 최대 허용값

    Returns
    -------
    dict
        rgb_image:
            원본 PIL 이미지

        predicted_depth:
            원본 해상도로 복원된 metric depth
            단위: meter

        raw_prediction_shape:
            모델의 원본 출력 shape

        original_size:
            원본 이미지 크기 (width, height)
    """

    # --------------------------------------------------------
    # 1. RGB 이미지 준비
    # --------------------------------------------------------
    if isinstance(rgb_input, (str, Path)):
        rgb_path = Path(rgb_input)

        if not rgb_path.exists():
            raise FileNotFoundError(
                f"RGB 이미지를 찾을 수 없습니다: {rgb_path}"
            )

        with Image.open(rgb_path) as image:
            rgb_image = image.convert("RGB")

    elif isinstance(rgb_input, Image.Image):
        rgb_image = rgb_input.convert("RGB")

    else:
        raise TypeError(
            "rgb_input은 이미지 경로 또는 PIL.Image여야 합니다."
        )

    original_width, original_height = rgb_image.size

    # --------------------------------------------------------
    # 2. 전처리
    # --------------------------------------------------------
    inputs = image_processor(
        images=rgb_image,
        return_tensors="pt",
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    # --------------------------------------------------------
    # 3. 추론
    # --------------------------------------------------------
    model.eval()

    with torch.inference_mode():
        outputs = model(**inputs)

    predicted_depth = outputs.predicted_depth

    raw_prediction_shape = tuple(
        predicted_depth.shape
    )

    # --------------------------------------------------------
    # 4. 원본 크기로 복원
    # --------------------------------------------------------
    predicted_depth_resized = F.interpolate(
        predicted_depth.unsqueeze(1),
        size=(
            original_height,
            original_width,
        ),
        mode="bicubic",
        align_corners=False,
    )

    predicted_depth_resized = (
        predicted_depth_resized
        .squeeze(0)
        .squeeze(0)
        .detach()
        .cpu()
        .numpy()
        .astype(np.float32)
    )

    # --------------------------------------------------------
    # 5. 수치 검증
    # --------------------------------------------------------
    if predicted_depth_resized.shape != (
        original_height,
        original_width,
    ):
        raise ValueError(
            "Metric prediction shape가 "
            "원본 이미지 크기와 다릅니다."
        )

    if not np.isfinite(
        predicted_depth_resized
    ).all():
        raise ValueError(
            "Metric prediction에 NaN 또는 Inf가 있습니다."
        )

    # bicubic 보간으로 인한 작은 범위 초과를 제한
    predicted_depth_resized = np.clip(
        predicted_depth_resized,
        a_min=min_depth,
        a_max=max_depth,
    )

    # Relative 모델에서는 출력 범위를 그대로 보존했지만
    # metric 모델에서는 출력의 의미가 명확
    # -> 음수 : 물리적으로 무효 / 최대 깊이인 80보다 큰 값 : 현재 평가 범위 밖
    # 따라서 범위 제한하는 과정이 필요

    return {
        "rgb_image": rgb_image,
        "predicted_depth": predicted_depth_resized,
        "raw_prediction_shape": raw_prediction_shape,
        "original_size": (
            original_width,
            original_height,
        ),
    }

# 이미지 한 장으로 metric 추론 확인
metric_sample_pair = test_subset_pairs[0]

metric_result = predict_metric_depth(
    rgb_input=metric_sample_pair["rgb"],
    model=metric_model,
    image_processor=metric_image_processor,
    device=device,
    min_depth=1e-3,
    max_depth=MAX_DEPTH,
)

metric_prediction = metric_result[
    "predicted_depth"
]

print(
    "Original size       :",
    metric_result["original_size"],
)

print(
    "Raw prediction shape:",
    metric_result["raw_prediction_shape"],
)

print(
    "Final prediction    :",
    metric_prediction.shape,
)

print(
    "Prediction min      :",
    metric_prediction.min(),
)

print(
    "Prediction max      :",
    metric_prediction.max(),
)

print(
    "Prediction mean     :",
    metric_prediction.mean(),
)

print(
    "Finite values       :",
    np.isfinite(metric_prediction).all(),
)

# relative 모델과 다르게 실제 거리 범위로 나타나야 함

# RGB*GT*Metric prediction 시각화
# GT, Prediction 모두 미터 단위 -> 같은 색상 범위

metric_sample = load_kitti_sample(
    metric_sample_pair,
    max_depth=MAX_DEPTH,
)

metric_gt = metric_sample["depth_gt"]
metric_valid_mask = metric_sample["valid_mask"]

metric_gt_masked = np.ma.masked_where(
    ~metric_valid_mask,
    metric_gt,
)

fig, axes = plt.subplots(
    1,
    3,
    figsize=(18, 5),
)

axes[0].imshow(
    metric_sample["rgb_image"]
)
axes[0].set_title("RGB Image")
axes[0].axis("off")

gt_plot = axes[1].imshow(
    metric_gt_masked,
    cmap="turbo",
    vmin=0,
    vmax=MAX_DEPTH,
)

axes[1].set_title(
    "KITTI Ground Truth (m)"
)
axes[1].axis("off")

fig.colorbar(
    gt_plot,
    ax=axes[1],
    fraction=0.046,
    pad=0.04,
)

pred_plot = axes[2].imshow(
    metric_prediction,
    cmap="turbo",
    vmin=0,
    vmax=MAX_DEPTH,
)

axes[2].set_title(
    "Depth Anything V2\n"
    "Metric Outdoor Prediction (m)"
)
axes[2].axis("off")

fig.colorbar(
    pred_plot,
    ax=axes[2],
    fraction=0.046,
    pad=0.04,
)

plt.tight_layout()
plt.show()

"""사용할 지표

| 지표     | 의미                    | 좋은 방향   |
| ------ | --------------------- | ------- |
| MAE    | 평균 절대 오차              | 낮을수록 좋음 |
| RMSE   | 큰 오차에 민감한 평균 오차       | 낮을수록 좋음 |
| AbsRel | GT 대비 상대 오차           | 낮을수록 좋음 |
| SqRel  | 제곱 오차를 GT로 나눈 값       | 낮을수록 좋음 |
| δ1     | 예측 비율 오차가 (1.25) 이내   | 높을수록 좋음 |
| δ2     | 예측 비율 오차가 (1.25^2) 이내 | 높을수록 좋음 |
| δ3     | 예측 비율 오차가 (1.25^3) 이내 | 높을수록 좋음 |

"""

# Metric 평가 지표 함수
def compute_depth_metrics(
    ground_truth,
    prediction,
    valid_mask,
    min_depth=1e-3,
    max_depth=80.0,
):
    """
    KITTI 유효 픽셀에서 metric depth 지표를 계산합니다.
    """

    ground_truth = np.asarray(
        ground_truth,
        dtype=np.float64,
    )

    prediction = np.asarray(
        prediction,
        dtype=np.float64,
    )

    valid_mask = np.asarray(
        valid_mask,
        dtype=bool,
    )

    if ground_truth.shape != prediction.shape:
        raise ValueError(
            "GT와 prediction shape가 다릅니다."
        )

    if ground_truth.shape != valid_mask.shape:
        raise ValueError(
            "GT와 valid mask shape가 다릅니다."
        )

    evaluation_mask = (
        valid_mask
        & np.isfinite(ground_truth)
        & np.isfinite(prediction)
        & (ground_truth > min_depth)
        & (ground_truth <= max_depth)
    )

    valid_count = int(
        evaluation_mask.sum()
    )

    if valid_count == 0:
        raise ValueError(
            "평가할 유효 픽셀이 없습니다."
        )

    gt = ground_truth[evaluation_mask]

    pred = prediction[evaluation_mask]

    pred = np.clip(
        pred,
        min_depth,
        max_depth,
    )

    absolute_error = np.abs(
        pred - gt
    )

    squared_error = (
        pred - gt
    ) ** 2

    mae = np.mean(
        absolute_error
    )

    rmse = np.sqrt(
        np.mean(squared_error)
    )

    abs_rel = np.mean(
        absolute_error / gt
    )

    sq_rel = np.mean(
        squared_error / gt
    )

    ratio = np.maximum(
        gt / pred,
        pred / gt,
    )

    delta_1 = np.mean(
        ratio < 1.25
    )

    delta_2 = np.mean(
        ratio < 1.25 ** 2
    )

    delta_3 = np.mean(
        ratio < 1.25 ** 3
    )

    return {
        "valid_pixel_count": valid_count,
        "mae": float(mae),
        "rmse": float(rmse),
        "abs_rel": float(abs_rel),
        "sq_rel": float(sq_rel),
        "delta_1": float(delta_1),
        "delta_2": float(delta_2),
        "delta_3": float(delta_3),
    }

# 한 장의 평가 결과 확인
single_metric_result = compute_depth_metrics(
    ground_truth=metric_gt,
    prediction=metric_prediction,
    valid_mask=metric_valid_mask,
    min_depth=1e-3,
    max_depth=MAX_DEPTH,
)

for metric_name, metric_value in (
    single_metric_result.items()
):
    if metric_name == "valid_pixel_count":
        print(
            f"{metric_name:20s}: "
            f"{metric_value}"
        )
    else:
        print(
            f"{metric_name:20s}: "
            f"{metric_value:.6f}"
        )

"""- MAE 6.69m: 유효 GT 픽셀에서 평균 절대 거리 오차가 약 6.69m

- RMSE 11.55m: MAE보다 상당히
크므로 일부 픽셀에서 큰 거리 오차 존재.

- AbsRel 0.274: GT 거리 대비 평균 절대 상대 오차가 약 27.4%

- δ1 0.425: 전체 유효 픽셀 중 약 42.5%가 GT의 1.25배 이내에

- δ2 0.732: 약 73.2%가 1.25^2배 이내

- δ3 0.878: 약 87.8%가 1.25
^3배 이내
"""

# Test subset 전체 Metric Baseline 평가
# 100장 순서대로 추론 후 이미지별 지표 저장

# ============================================================
# 1. 저장 폴더
# ============================================================
METRIC_BASELINE_ROOT = (
    PROJECT_ROOT
    / "outputs"
    / "metric_baseline"
)

METRIC_PREDICTION_DIR = (
    METRIC_BASELINE_ROOT
    / "predictions"
)

METRIC_VISUALIZATION_DIR = (
    METRIC_BASELINE_ROOT
    / "visualizations"
)

METRIC_PREDICTION_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

METRIC_VISUALIZATION_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# 2. 전체 test subset 평가
# ============================================================
metric_records = []

total_samples = len(test_subset_pairs)

print(
    f"총 {total_samples}개 test sample의 "
    "Metric Baseline 평가를 시작합니다.\n"
)

for sample_index, pair in enumerate(
    test_subset_pairs
):
    # --------------------------------------------------------
    # KITTI GT 불러오기
    # --------------------------------------------------------
    sample = load_kitti_sample(
        pair=pair,
        max_depth=MAX_DEPTH,
    )

    # --------------------------------------------------------
    # Metric depth 추론
    # --------------------------------------------------------
    prediction_result = predict_metric_depth(
        rgb_input=sample["rgb_image"],
        model=metric_model,
        image_processor=metric_image_processor,
        device=device,
        min_depth=1e-3,
        max_depth=MAX_DEPTH,
    )

    predicted_depth = prediction_result[
        "predicted_depth"
    ]

    # --------------------------------------------------------
    # 평가 지표 계산
    # --------------------------------------------------------
    metrics = compute_depth_metrics(
        ground_truth=sample["depth_gt"],
        prediction=predicted_depth,
        valid_mask=sample["valid_mask"],
        min_depth=1e-3,
        max_depth=MAX_DEPTH,
    )

    # --------------------------------------------------------
    # Prediction 저장
    # --------------------------------------------------------
    prediction_path = (
        METRIC_PREDICTION_DIR
        / f"sample_{sample_index:03d}_pred_metric.npy"
    )

    np.save(
        prediction_path,
        predicted_depth.astype(np.float32),
    )

    # --------------------------------------------------------
    # 메타데이터 구성
    # --------------------------------------------------------
    record = {
        "sample_index": sample_index,
        "sequence": sample["sequence"],
        "frame": sample["frame"],
        "rgb_path": str(sample["rgb_path"]),
        "depth_path": str(sample["depth_path"]),
        "prediction_path": str(prediction_path),
        "image_width": sample["rgb_image"].size[0],
        "image_height": sample["rgb_image"].size[1],
        "valid_pixel_rate": float(
            sample["valid_mask"].mean()
        ),
        "prediction_min": float(
            predicted_depth.min()
        ),
        "prediction_max": float(
            predicted_depth.max()
        ),
        "prediction_mean": float(
            predicted_depth.mean()
        ),
        **metrics,
    }

    metric_records.append(record)

    # --------------------------------------------------------
    # 진행 상황 표시
    # --------------------------------------------------------
    if (
        sample_index == 0
        or (sample_index + 1) % 10 == 0
        or sample_index + 1 == total_samples
    ):
        print(
            f"[{sample_index + 1:03d}/{total_samples:03d}] "
            f"AbsRel={metrics['abs_rel']:.4f}, "
            f"RMSE={metrics['rmse']:.4f}, "
            f"δ1={metrics['delta_1']:.4f}"
        )


# ============================================================
# 3. DataFrame 및 CSV 저장
# ============================================================
metric_baseline_df = pd.DataFrame(
    metric_records
)

METRIC_RESULT_CSV_PATH = (
    METRIC_BASELINE_ROOT
    / "metric_baseline_per_image.csv"
)

metric_baseline_df.to_csv(
    METRIC_RESULT_CSV_PATH,
    index=False,
    encoding="utf-8-sig",
)

if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("\n전체 Metric Baseline 평가 완료")
print("CSV 저장 위치:", METRIC_RESULT_CSV_PATH)

"""전체 평균 지표 계산

**Image-average**

각 이미지의 지표를 먼저 계산한 뒤 100장의 평균을 구함. 각 이미지가 동일한 가중치
**Pixel-weighted**

모든 이미지의 유효 픽셀 수를 고려해 가중 평균을 냄. GT가 많은 이미지가 더 큰 영향
"""

# 전체 평균 지표 계산
METRIC_COLUMNS = [
    "mae",
    "rmse",
    "abs_rel",
    "sq_rel",
    "delta_1",
    "delta_2",
    "delta_3",
]


# ============================================================
# 1. 이미지 단위 단순 평균
# ============================================================
image_average = (
    metric_baseline_df[
        METRIC_COLUMNS
    ]
    .mean()
)


# ============================================================
# 2. 유효 픽셀 수 기준 가중 평균
# ============================================================
pixel_weights = (
    metric_baseline_df[
        "valid_pixel_count"
    ].to_numpy(
        dtype=np.float64
    )
)

pixel_weighted_average = {}

for metric_name in METRIC_COLUMNS:
    pixel_weighted_average[
        metric_name
    ] = np.average(
        metric_baseline_df[
            metric_name
        ].to_numpy(
            dtype=np.float64
        ),
        weights=pixel_weights,
    )


# ============================================================
# 3. 요약 DataFrame
# ============================================================
metric_summary_df = pd.DataFrame(
    [
        {
            "aggregation": "image_average",
            "sample_count": len(
                metric_baseline_df
            ),
            "valid_pixel_count": int(
                metric_baseline_df[
                    "valid_pixel_count"
                ].sum()
            ),
            **image_average.to_dict(),
        },
        {
            "aggregation": "pixel_weighted_average",
            "sample_count": len(
                metric_baseline_df
            ),
            "valid_pixel_count": int(
                metric_baseline_df[
                    "valid_pixel_count"
                ].sum()
            ),
            **pixel_weighted_average,
        },
    ]
)

METRIC_SUMMARY_CSV_PATH = (
    METRIC_BASELINE_ROOT
    / "metric_baseline_summary.csv"
)

metric_summary_df.to_csv(
    METRIC_SUMMARY_CSV_PATH,
    index=False,
    encoding="utf-8-sig",
)

display(
    metric_summary_df.round(6)
)

print(
    "Summary CSV:",
    METRIC_SUMMARY_CSV_PATH,
)

# 정확한 Global Metric 계산
# 저장된 prediction을 다시 읽어 모든 유효 픽셀의 오차 합을 누적합
# 메모리에 모든 픽셀 한꺼번에 올리지 않아서 안전

def compute_global_depth_metrics(
    pairs,
    prediction_dir,
    max_depth=80.0,
    min_depth=1e-3,
):
    """
    여러 이미지의 유효 픽셀 통계를 누적하여
    정확한 global depth metrics를 계산합니다.
    """

    valid_pixel_count = 0

    absolute_error_sum = 0.0
    squared_error_sum = 0.0
    abs_rel_sum = 0.0
    sq_rel_sum = 0.0

    delta_1_count = 0
    delta_2_count = 0
    delta_3_count = 0

    for sample_index, pair in enumerate(pairs):
        sample = load_kitti_sample(
            pair=pair,
            max_depth=max_depth,
        )

        prediction_path = (
            prediction_dir
            / (
                f"sample_{sample_index:03d}"
                "_pred_metric.npy"
            )
        )

        if not prediction_path.exists():
            raise FileNotFoundError(
                f"Prediction 파일이 없습니다: "
                f"{prediction_path}"
            )

        prediction = np.load(
            prediction_path
        ).astype(np.float64)

        ground_truth = sample[
            "depth_gt"
        ].astype(np.float64)

        valid_mask = (
            sample["valid_mask"]
            & np.isfinite(ground_truth)
            & np.isfinite(prediction)
            & (ground_truth > min_depth)
            & (ground_truth <= max_depth)
        )

        gt = ground_truth[valid_mask]

        pred = np.clip(
            prediction[valid_mask],
            min_depth,
            max_depth,
        )

        error = pred - gt
        absolute_error = np.abs(error)
        squared_error = error ** 2

        ratio = np.maximum(
            gt / pred,
            pred / gt,
        )

        current_count = gt.size

        valid_pixel_count += current_count
        absolute_error_sum += absolute_error.sum()
        squared_error_sum += squared_error.sum()
        abs_rel_sum += (
            absolute_error / gt
        ).sum()
        sq_rel_sum += (
            squared_error / gt
        ).sum()

        delta_1_count += np.sum(
            ratio < 1.25
        )
        delta_2_count += np.sum(
            ratio < 1.25 ** 2
        )
        delta_3_count += np.sum(
            ratio < 1.25 ** 3
        )

    if valid_pixel_count == 0:
        raise ValueError(
            "전체 유효 픽셀 수가 0입니다."
        )

    return {
        "sample_count": len(pairs),
        "valid_pixel_count": int(
            valid_pixel_count
        ),
        "mae": float(
            absolute_error_sum
            / valid_pixel_count
        ),
        "rmse": float(
            np.sqrt(
                squared_error_sum
                / valid_pixel_count
            )
        ),
        "abs_rel": float(
            abs_rel_sum
            / valid_pixel_count
        ),
        "sq_rel": float(
            sq_rel_sum
            / valid_pixel_count
        ),
        "delta_1": float(
            delta_1_count
            / valid_pixel_count
        ),
        "delta_2": float(
            delta_2_count
            / valid_pixel_count
        ),
        "delta_3": float(
            delta_3_count
            / valid_pixel_count
        ),
    }


global_metrics = compute_global_depth_metrics(
    pairs=test_subset_pairs,
    prediction_dir=METRIC_PREDICTION_DIR,
    max_depth=MAX_DEPTH,
    min_depth=1e-3,
)

print("Global Metric Baseline")
print("-" * 35)

for metric_name, metric_value in (
    global_metrics.items()
):
    if metric_name in [
        "sample_count",
        "valid_pixel_count",
    ]:
        print(
            f"{metric_name:20s}: "
            f"{metric_value}"
        )
    else:
        print(
            f"{metric_name:20s}: "
            f"{metric_value:.6f}"
        )

# csv로 저장
GLOBAL_METRIC_CSV_PATH = (
    METRIC_BASELINE_ROOT
    / "metric_baseline_global.csv"
)

pd.DataFrame(
    [global_metrics]
).to_csv(
    GLOBAL_METRIC_CSV_PATH,
    index=False,
    encoding="utf-8-sig",
)

print(
    "Global CSV 저장 위치:",
    GLOBAL_METRIC_CSV_PATH,
)

