# -*- coding: utf-8 -*-
"""02_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjXSZYoZn3niOnX4eLxful17SselvwYm
"""

from google.colab import drive

drive.mount("/content/drive", force_remount=False)

import sys
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/2026/comento/week4"
)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )

print("PROJECT_ROOT:", PROJECT_ROOT)
print("Exists      :", PROJECT_ROOT.exists())

import torch

import utils.config as config_utils
import utils.initialization as init_utils
import utils.training as training_utils
import utils.inference as inference_utils
import utils.metrics as metrics_utils
import utils.visualization as visualization_utils

print("PyTorch:", torch.__version__)
print("Device :", config_utils.DEVICE)
print("Dataset root:", config_utils.DATASET_ROOT)

# TAR 데이터 복원
dataset_root = init_utils.prepare_local_dataset(
    force_extract=False,
)

print("Dataset root:", dataset_root)
print(
    "Train exists:",
    (dataset_root / "train").is_dir(),
)
print(
    "Test exists :",
    (dataset_root / "test").is_dir(),
)

# Dataset과 DataLoader 초기화
resources = init_utils.initialize_project(
    load_model=False,
    check_exists=True,
    num_workers=0,
)

train_loader = resources["train_loader"]
val_loader = resources["val_loader"]
test_loader = resources["test_loader"]

train_dataset = resources["train_dataset"]
val_dataset = resources["val_dataset"]
test_dataset = resources["test_dataset"]

print("Dataset sizes")
print("Train:", len(train_dataset))
print("Val  :", len(val_dataset))
print("Test :", len(test_dataset))

print("\nBatch counts")
print("Train:", len(train_loader))
print("Val  :", len(val_loader))
print("Test :", len(test_loader))

# 배치 검증
train_batch = next(
    iter(train_loader)
)

print("Batch keys:", train_batch.keys())

print(
    "Image:",
    train_batch["image"].shape,
    train_batch["image"].dtype,
)

print(
    "Depth:",
    train_batch["depth"].shape,
    train_batch["depth"].dtype,
)

print(
    "Mask :",
    train_batch["valid_mask"].shape,
    train_batch["valid_mask"].dtype,
)

print(
    "Valid ratio:",
    train_batch["valid_mask"]
    .float()
    .mean()
    .item(),
)

# fine-tuning용 모델 로드
# Metric Outdoor

model, image_processor = (
    init_utils.load_depth_model(
        model_name=config_utils.METRIC_MODEL_NAME,
        device=config_utils.DEVICE,
    )
)

print("Model class    :", type(model).__name__)
print("Processor class:", type(image_processor).__name__)
print(
    "Model device   :",
    next(model.parameters()).device,
)
print("Training mode  :", model.training)

# 모델 구조 확인

print("Top-level modules")
print("-" * 60)

for module_name, module in model.named_children():
    print(
        f"{module_name:25s}",
        type(module).__name__,
    )

# backbone 존재 여부 확인
print(
    "Has backbone:",
    hasattr(model, "backbone"),
)

print(
    "Has neck:",
    hasattr(model, "neck"),
)

print(
    "Has head:",
    hasattr(model, "head"),
)

"""```
RGB Image
      │
      ▼
Dinov2 Backbone        ← 특징(feature) 추출
      │
      ▼
DepthAnything Neck     ← 여러 feature를 융합
      │
      ▼
Depth Head             ← depth map 생성
```

**Backbone(Dinov2)**

이미 대규모 데이터로 학습된 Vision Transformer

fine-tuning 시 : 여기를 크게 학습 시키면 학습 시간 증가 & GPU 메모리 증가 & 작은 데이터셋에서 성능 저하

**Neck(DepthAnythingNeck)**

Depth Anything에서 사용하는 여러 feature map을 depth estimation에 적합하게 합치는 부분

fine-tuning 시 : 학습

**Head(DepthAnythingDepthEstimationHead)**

최종 depth map 생성

fint-tuning 시 : 학습
"""

# model1.backbone이 실제로 존재하는 경우 backbone만 고정
# backbone 있음 (Dinov2Backbone)
if not hasattr(model, "backbone"):
    raise AttributeError(
        "모델에서 backbone 모듈을 찾지 못했습니다. "
        "앞의 named_children() 출력을 확인해야 합니다."
    )

for parameter in model.backbone.parameters():
    parameter.requires_grad = False


# 파라미터 수 확인
parameter_counts = (
    init_utils.count_model_parameters(
        model
    )
)

for key, value in parameter_counts.items():
    print(
        f"{key:22s}: {value:,}"
    )

trainable_ratio = (
    parameter_counts["trainable_parameters"]
    / parameter_counts["total_parameters"]
)

print(
    f"Trainable ratio       : "
    f"{trainable_ratio:.2%}"
)

# trainable_parameters가 0이면 잘못 고정한 것
# total_parameters와 같으면 backbone이 고정되지 않은 것

# Optimizer 생성
# Backbone을 고정한 후에 optimizer를 만들어야 함
optimizer = training_utils.create_optimizer(
    model=model,
    learning_rate=config_utils.LEARNING_RATE,
    weight_decay=config_utils.WEIGHT_DECAY,
)

print(
    "Optimizer:",
    type(optimizer).__name__,
)

print(
    "Learning rate:",
    optimizer.param_groups[0]["lr"],
)

optimizer_parameter_count = sum(
    parameter.numel()
    for group in optimizer.param_groups
    for parameter in group["params"]
)

print(
    "Optimizer parameters:",
    f"{optimizer_parameter_count:,}",
)

# Optimizer가 frozen parameter를 제외하고 학습 가능한 parameter만 포함하는지 확인하는 단계

# 한 배치 forward와 loss 검증
# parameter 업데이트하지 않고 확인
model.eval()

with torch.no_grad():
    forward_result = (
        training_utils.forward_depth_batch(
            model=model,
            batch=train_batch,
            image_processor=image_processor,
            device=config_utils.DEVICE,
        )
    )

    smoke_loss = (
        training_utils.masked_l1_loss(
            predicted_depth=forward_result[
                "predicted_depth"
            ],
            target_depth=forward_result[
                "target_depth"
            ],
            valid_mask=forward_result[
                "valid_mask"
            ],
        )
    )

print(
    "Pixel values:",
    forward_result["pixel_values"].shape,
)

print(
    "Prediction  :",
    forward_result["predicted_depth"].shape,
)

print(
    "Target      :",
    forward_result["target_depth"].shape,
)

print(
    "Mask        :",
    forward_result["valid_mask"].shape,
)

print(
    "Initial masked L1 loss:",
    float(smoke_loss.item()),
)

# 한 배치 실제 학습 smoke test
# 여기서 처음으로 backward와 optimizer step까지 확인
smoke_train_result = (
    training_utils.train_one_epoch(
        model=model,
        dataloader=train_loader,
        optimizer=optimizer,
        image_processor=image_processor,
        device=config_utils.DEVICE,
        max_batches=1,
    )
)

print("Smoke train result")
print(smoke_train_result)

# validation도 한 배치만 확인
smoke_val_result = (
    training_utils.validate_one_epoch(
        model=model,
        dataloader=val_loader,
        image_processor=image_processor,
        device=config_utils.DEVICE,
        max_batches=1,
    )
)

print("Smoke validation result")
print(smoke_val_result)

"""학습 시작"""

# 한 배치 smoke test를 실행하면 모델 parameter가 실제로 한 번 업데이트
# 정식 학습 시작하기 전에는 모델과 optimizer까지 새로 생성하는 것이 가장 확실

del model
del optimizer

if torch.cuda.is_available():
    torch.cuda.empty_cache()

# 정식 학습 모델 새로 로드
model, image_processor = (
    init_utils.load_depth_model(
        model_name=config_utils.METRIC_MODEL_NAME,
        device=config_utils.DEVICE,
    )
)

print("Model:", type(model).__name__)
print("Device:", next(model.parameters()).device)

# Backbone을 다시 고정
for parameter in model.backbone.parameters():
    parameter.requires_grad = False

parameter_counts = (
    init_utils.count_model_parameters(model)
)

for key, value in parameter_counts.items():
    print(f"{key:22s}: {value:,}")

trainable_ratio = (
    parameter_counts["trainable_parameters"]
    / parameter_counts["total_parameters"]
)

print(f"Trainable ratio       : {trainable_ratio:.2%}")
# 이전 결과인 11.01%와 유사한 결과가 나와야 함

# 정식 optimizer와 scheduler 생성
# learning_rate = 1e-4로 시작하되,
# validation loss가 정체되면 learning rate를 낮추는 scheduler 사용

optimizer = training_utils.create_optimizer(
    model=model,
    learning_rate=config_utils.LEARNING_RATE,
    weight_decay=config_utils.WEIGHT_DECAY,
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=1,
    min_lr=1e-6,
)

print("Optimizer :", type(optimizer).__name__)
print("Scheduler :", type(scheduler).__name__)
print("Initial LR:", optimizer.param_groups[0]["lr"])

# 학습 결과 저장 경로 설정

FINETUNE_ROOT = (
    config_utils.OUTPUT_ROOT
    / "finetuning"
)

FINETUNE_CHECKPOINT_DIR = (
    config_utils.CHECKPOINT_ROOT
    / "finetuning"
)

FINETUNE_LOG_DIR = (
    config_utils.LOG_ROOT
    / "finetuning"
)

for directory in [
    FINETUNE_ROOT,
    FINETUNE_CHECKPOINT_DIR,
    FINETUNE_LOG_DIR,
]:
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )

BEST_CHECKPOINT_PATH = (
    FINETUNE_CHECKPOINT_DIR
    / "best_model.pt"
)

LAST_CHECKPOINT_PATH = (
    FINETUNE_CHECKPOINT_DIR
    / "last_model.pt"
)

print("Best checkpoint:", BEST_CHECKPOINT_PATH)

# 실제 Fine-tunint 설정
# 현재 데이터 규모 Train = 500 / Validation = 100 / Test = 100
NUM_EPOCHS = 20
EARLY_STOPPING_PATIENCE = 5
MIN_DELTA = 1e-4

# 실제 학습 실행
import json
import time
import pandas as pd
from tqdm.auto import tqdm

history = {
    "epoch": [],
    "train_loss": [],
    "val_loss": [],
    "learning_rate": [],
    "epoch_seconds": [],
}

best_val_loss = float("inf")
best_epoch = 0
epochs_without_improvement = 0

epoch_progress = tqdm(
    range(1, NUM_EPOCHS + 1),
    desc="Fine-tuning",
    unit="epoch",
)

for epoch in range(1, NUM_EPOCHS + 1):
    epoch_start = time.time()

    print(f"\nEpoch {epoch:02d}/{NUM_EPOCHS:02d}")

    train_result = training_utils.train_one_epoch(
        model=model,
        dataloader=train_loader,
        optimizer=optimizer,
        image_processor=image_processor,
        device=config_utils.DEVICE,
        gradient_clip_norm=(
            config_utils.GRADIENT_CLIP_NORM
        ),
        max_batches=None,
    )

    val_result = training_utils.validate_one_epoch(
        model=model,
        dataloader=val_loader,
        image_processor=image_processor,
        device=config_utils.DEVICE,
        max_batches=None,
    )

    train_loss = float(train_result["loss"])
    val_loss = float(val_result["loss"])

    scheduler.step(val_loss)

    current_lr = float(
        optimizer.param_groups[0]["lr"]
    )

    epoch_seconds = (
        time.time() - epoch_start
    )

    history["epoch"].append(epoch)
    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)
    history["learning_rate"].append(current_lr)
    history["epoch_seconds"].append(epoch_seconds)

    # --------------------------------------------------------
    # Best checkpoint 판정
    # --------------------------------------------------------
    improved =val_loss < best_val_loss - MIN_DELTA

    if improved:
        best_val_loss = val_loss
        best_epoch = epoch
        epochs_without_improvement = 0

        training_utils.save_checkpoint(
            model=model,
            optimizer=optimizer,
            scheduler=scheduler,
            epoch=epoch,
            train_loss=train_loss,
            val_loss=val_loss,
            checkpoint_path=BEST_CHECKPOINT_PATH,
            extra_state={
                "best_epoch": best_epoch,
                "best_val_loss": best_val_loss,
                "history": history,
                "model_name": (
                    config_utils.METRIC_MODEL_NAME
                ),
                "backbone_frozen": True,
            },
        )

        checkpoint_message = "Best model 저장"

    else:
        epochs_without_improvement += 1

        print(
            "Validation improvement 없음: "
            f"{epochs_without_improvement}/"
            f"{EARLY_STOPPING_PATIENCE}"
        )

    # 매 epoch마다 마지막 상태 저장
    training_utils.save_checkpoint(
        model=model,
        optimizer=optimizer,
        scheduler=scheduler,
        epoch=epoch,
        train_loss=train_loss,
        val_loss=val_loss,
        checkpoint_path=LAST_CHECKPOINT_PATH,
        extra_state={
            "best_epoch": best_epoch,
            "best_val_loss": best_val_loss,
            "history": history,
            "model_name": config_utils.METRIC_MODEL_NAME,
            "backbone_frozen": True,
        },
    )

    # 로그도 매 epoch 저장
    history_df = pd.DataFrame(history)

    history_df.to_csv(
        FINETUNE_LOG_DIR / "training_history.csv",
        index=False,
        encoding="utf-8-sig",
    )

    with open(
        FINETUNE_LOG_DIR / "training_history.json",
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            history,
            file,
            ensure_ascii=False,
            indent=2,
        )

    epoch_progress.set_postfix(
        train=f"{train_loss:.4f}",
        val=f"{val_loss:.4f}",
        lr=f"{current_lr:.2e}",
        best=f"{best_val_loss:.4f}",
        )

    tqdm.write(
        f"Train loss : {train_loss:.6f}\n"
        f"Val loss   : {val_loss:.6f}\n"
        f"LR         : {current_lr:.8f}\n"
        f"Time       : {epoch_seconds / 60:.2f}분\n"
        f"Status     : {checkpoint_message}"
    )

    if (
        epochs_without_improvement
        >= EARLY_STOPPING_PATIENCE
    ):
        print(
            "\nEarly stopping 실행: "
            f"Epoch {epoch}"
        )
        break

print("Fine-tuning 종료")
print("Best epoch   :", best_epoch)
print("Best val loss:", best_val_loss)
print("Best model   :", BEST_CHECKPOINT_PATH)

import pandas as pd

history_path = (
    config_utils.LOG_ROOT
    / "finetuning"
    / "training_history.csv"
)

history_df = pd.read_csv(history_path)
display(history_df)

# best epoch 7 확인

checkpoint = torch.load(
    BEST_CHECKPOINT_PATH,
    map_location="cpu",
    weights_only=False,
)

print("Best checkpoint epoch   :", checkpoint["epoch"])
print("Best checkpoint val loss:", checkpoint["val_loss"])
print("Train loss              :", checkpoint["train_loss"])

"""Best checkpoint epoch   : 7

Best checkpoint val loss: 1.4669304633140563

Train loss              : 1.7468677413463594
"""