# -*- coding: utf-8 -*-
"""04_relative_depth_comparision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9wpjWdyOcAsqGKJvFIaXtQkzfKEeSce

프로젝트 초기화
"""

from google.colab import drive

drive.mount(
    "/content/drive",
    force_remount=False,
)

import sys
from pathlib import Path

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/2026/comento/week4"
)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import time

import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

from tqdm.auto import tqdm

import utils.config as config_utils
import utils.initialization as init_utils
import utils.inference as inference_utils
import utils.metrics as metrics_utils
import utils.visualization as visualization_utils

print("Device:", config_utils.DEVICE)

# KITTI 데이터 복원 및 TestLoader 준비
dataset_root = init_utils.prepare_local_dataset(
    force_extract=False,
)

print("Dataset root:", dataset_root)

resources = init_utils.initialize_project(
    load_model=False,
    check_exists=True,
    num_workers=0,
)
train_dataset = resources["train_dataset"]
val_dataset = resources["val_dataset"]
test_dataset = resources["test_dataset"]

print("Test samples:", len(test_dataset))

# 대표 샘플
REPRESENTATIVE_INDICES = {
    "best": 83,
    "average": 90,
    "failure": 73,
}

"""대표 KITTI 이미지 83, 90, 73 로드

→ Virtual Depth 생성

→ MiDaS 추론

→ DA V2 Before/After 결과 로드

→ 정성 비교

- Virtual Depth: 밝기값 기반 pseudo point cloud
- MiDaS: 상대 깊이 기반 pseudo point cloud
- DA V2 Before/After: metric depth 기반 pseudo point cloud

    **calibration이 없으므로 DA V2도 정밀한 3D 복원은 아님**

### Virtual Depth
"""

# 2주차 Virtual Depth 함수 그대로 사용
import cv2
import numpy as np


def generate_virtual_depth(
    rgb_image: np.ndarray,
) -> np.ndarray:
    """
    RGB 이미지의 grayscale 밝기값을
    가상의 상대 깊이값으로 사용합니다.

    Parameters
    ----------
    rgb_image : np.ndarray
        [H, W, 3] RGB 이미지, 범위 0~1 또는 0~255

    Returns
    -------
    np.ndarray
        [H, W] uint8 virtual depth map
    """

    if rgb_image is None:
        raise ValueError(
            "입력된 이미지가 없습니다."
        )

    rgb_image = np.asarray(rgb_image)

    if (
        rgb_image.ndim != 3
        or rgb_image.shape[2] != 3
    ):
        raise ValueError(
            "RGB 이미지는 [H, W, 3] 형태여야 합니다."
        )

    if rgb_image.max() <= 1.0:
        rgb_uint8 = np.clip(
            rgb_image * 255.0,
            0,
            255,
        ).astype(np.uint8)
    else:
        rgb_uint8 = np.clip(
            rgb_image,
            0,
            255,
        ).astype(np.uint8)

    virtual_depth = cv2.cvtColor(
        rgb_uint8,
        cv2.COLOR_RGB2GRAY,
    )

    return virtual_depth

virtual_depth_results = {}

for category, sample_index in (
    REPRESENTATIVE_INDICES.items()
):
    sample = test_dataset[sample_index]

    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
    )

    virtual_depth = generate_virtual_depth(
        rgb_image
    )

    virtual_depth_results[
        sample_index
    ] = virtual_depth

    print(
        category,
        sample_index,
        virtual_depth.shape,
        virtual_depth.min(),
        virtual_depth.max(),
    )

# RGB와 Virtual Depth 저장
import matplotlib.pyplot as plt


VIRTUAL_DEPTH_ROOT = (
    config_utils.OUTPUT_ROOT
    / "relative_depth_comparison"
    / "virtual_depth"
)

VIRTUAL_DEPTH_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in (
    REPRESENTATIVE_INDICES.items()
):
    sample = test_dataset[sample_index]

    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
    )

    virtual_depth = (
        virtual_depth_results[
            sample_index
        ]
    )

    figure, axes = plt.subplots(
        1,
        3,
        figsize=(16, 5),
    )

    axes[0].imshow(
        rgb_image
    )
    axes[0].set_title(
        "RGB Image"
    )
    axes[0].axis("off")

    gray_handle = axes[1].imshow(
        virtual_depth,
        cmap="gray",
        vmin=0,
        vmax=255,
    )
    axes[1].set_title(
        "Virtual Depth — Grayscale"
    )
    axes[1].axis("off")

    figure.colorbar(
        gray_handle,
        ax=axes[1],
        fraction=0.046,
        pad=0.04,
        label="Brightness value",
    )

    color_handle = axes[2].imshow(
        virtual_depth,
        cmap="inferno",
        vmin=0,
        vmax=255,
    )
    axes[2].set_title(
        "Virtual Depth — Color Map"
    )
    axes[2].axis("off")

    figure.colorbar(
        color_handle,
        ax=axes[2],
        fraction=0.046,
        pad=0.04,
        label="Brightness value",
    )

    figure.suptitle(
        (
            f"{category.capitalize()} case "
            f"— Sample {sample_index}"
        )
    )

    figure.tight_layout(
        rect=[0, 0, 1, 0.94]
    )

    save_path = (
        VIRTUAL_DEPTH_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}_virtual_depth.png"
        )
    )

    figure.savefig(
        save_path,
        dpi=200,
        bbox_inches="tight",
    )

    np.save(
        VIRTUAL_DEPTH_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}_virtual_depth.npy"
        ),
        virtual_depth,
    )

    plt.show()
    plt.close(figure)

    print("저장 완료:", save_path)

# Virtual Depth Heatmap 저장

VIRTUAL_HEATMAP_ROOT = (
    config_utils.OUTPUT_ROOT
    / "relative_depth_comparison"
    / "virtual_depth"
    / "heatmaps"
)

VIRTUAL_HEATMAP_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in REPRESENTATIVE_INDICES.items():
    virtual_depth = virtual_depth_results[sample_index]

    figure, axis = plt.subplots(
        figsize=(8, 6)
    )

    heatmap_handle = axis.imshow(
        virtual_depth,
        cmap="inferno",
        vmin=0,
        vmax=255,
    )

    axis.set_title(
        f"{category.capitalize()} case — "
        f"Sample {sample_index}\n"
        "Brightness-based Virtual Depth"
    )

    axis.axis("off")

    colorbar = figure.colorbar(
        heatmap_handle,
        ax=axis,
        fraction=0.046,
        pad=0.04,
    )

    colorbar.set_label(
        "Virtual depth value (brightness)"
    )

    figure.tight_layout()

    save_path = (
        VIRTUAL_HEATMAP_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}_heatmap.png"
        )
    )

    figure.savefig(
        save_path,
        dpi=200,
        bbox_inches="tight",
    )

    plt.show()
    plt.close(figure)

    print("저장 완료:", save_path)

# Point cloud 생성
def virtual_depth_to_point_cloud(
    virtual_depth: np.ndarray,
    rgb: np.ndarray,
    stride: int = 2,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Virtual Depth를 brightness-based pseudo point cloud로 변환합니다.

    X, Y: 픽셀 좌표
    Z: grayscale 밝기값
    colors: 원본 RGB 색상
    """

    if virtual_depth.ndim != 2:
        raise ValueError(
            "virtual_depth는 [H, W] 형태여야 합니다."
        )

    if rgb.ndim != 3 or rgb.shape[2] != 3:
        raise ValueError(
            "rgb는 [H, W, 3] 형태여야 합니다."
        )

    if rgb.shape[:2] != virtual_depth.shape:
        raise ValueError(
            "RGB와 Virtual Depth 해상도가 일치하지 않습니다."
        )

    height, width = virtual_depth.shape

    y_coordinates, x_coordinates = np.mgrid[
        0:height:stride,
        0:width:stride,
    ]

    sampled_depth = virtual_depth[
        0:height:stride,
        0:width:stride,
    ].astype(np.float32)

    sampled_rgb = rgb[
        0:height:stride,
        0:width:stride,
    ].astype(np.float32)

    points = np.column_stack(
        [
            x_coordinates.ravel(),
            y_coordinates.ravel(),
            sampled_depth.ravel(),
        ]
    ).astype(np.float32)

    colors = sampled_rgb.reshape(
        -1,
        3,
    )

    return points, colors

def rgb_array_to_plotly_colors(
    colors: np.ndarray,
):
    """
    RGB 배열을 Plotly에서 사용할
    rgb(r,g,b) 문자열로 변환합니다.
    """

    colors = np.asarray(
        colors,
        dtype=np.float32,
    )

    if colors.max() <= 1.0:
        colors = colors * 255.0

    colors = np.clip(
        colors,
        0,
        255,
    ).astype(np.uint8)

    plotly_colors = [
        f"rgb({r},{g},{b})"
        for r, g, b in colors
    ]

    return plotly_colors

# Plotly 시각화
import plotly.graph_objects as go


def plot_virtual_depth_point_cloud(
    points: np.ndarray,
    colors: np.ndarray,
    title: str,
    save_html_path=None,
    marker_size: float = 1.5,
):
    plotly_colors = (
        rgb_array_to_plotly_colors(
            colors
        )
    )

    figure = go.Figure(
        data=[
            go.Scatter3d(
                x=points[:, 0],
                y=points[:, 1],
                z=points[:, 2],
                mode="markers",
                marker={
                    "size": marker_size,
                    "color": plotly_colors,
                    "opacity": 0.9,
                },
                hovertemplate=(
                    "Pixel X: %{x}<br>"
                    "Pixel Y: %{y}<br>"
                    "Brightness: %{z:.0f}"
                    "<extra></extra>"
                ),
            )
        ]
    )

    figure.update_layout(
        title={
            "text": title,
            "x": 0.5,
            "xanchor": "center",
        },
        scene={
            "xaxis_title": "Pixel X",
            "yaxis_title": "Pixel Y",
            "zaxis_title": "Brightness value",
            "yaxis": {
                "autorange": "reversed",
            },
            "aspectmode": "data",
        },
        height=750,
        margin={
            "l": 0,
            "r": 0,
            "t": 70,
            "b": 0,
        },
    )

    if save_html_path is not None:
        figure.write_html(
            str(save_html_path),
            include_plotlyjs=True,
            full_html=True,
        )

    figure.show()

    return figure

# 대표 사례 생성 및 저장
VIRTUAL_POINT_CLOUD_ROOT = (
    config_utils.OUTPUT_ROOT
    / "relative_depth_comparison"
    / "virtual_depth"
    / "point_clouds"
)

VIRTUAL_POINT_CLOUD_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in REPRESENTATIVE_INDICES.items():
    # 현재 대표 샘플 불러오기
    sample = test_dataset[sample_index]

    # [3, H, W] Tensor -> [H, W, 3] NumPy RGB
    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
        .astype(np.float32)
    )

    virtual_depth = virtual_depth_results[
        sample_index
    ]

    # Z축은 grayscale 밝기값,
    # Point 색상은 원본 RGB 사용
    points, colors = virtual_depth_to_point_cloud(
        virtual_depth=virtual_depth,
        rgb=rgb_image,
        stride=2,
    )

    sample_root = (
        VIRTUAL_POINT_CLOUD_ROOT
        / f"{category}_sample_{sample_index:03d}"
    )

    sample_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Point 좌표 저장
    np.save(
        sample_root / "virtual_points.npy",
        points,
    )

    # 원본 RGB 색상 저장
    np.save(
        sample_root / "virtual_colors.npy",
        colors,
    )

    html_path = (
        sample_root
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_virtual_point_cloud.html"
        )
    )

    plot_virtual_depth_point_cloud(
        points=points,
        colors=colors,
        title=(
            f"{category.capitalize()} case "
            f"— Sample {sample_index}<br>"
            "Brightness-based Virtual Depth Surface"
        ),
        save_html_path=html_path,
        marker_size=1.4,
    )

    print(
        f"저장 완료: {category}, "
        f"sample {sample_index}"
    )

"""### MiDaS 추론"""

# MiDas 모델 로드
import torch

from transformers import (
    DPTForDepthEstimation,
    DPTImageProcessor,
)


MIDAS_MODEL_NAME = "Intel/dpt-hybrid-midas"

MIDAS_DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

midas_processor = (
    DPTImageProcessor.from_pretrained(
        MIDAS_MODEL_NAME
    )
)

midas_model = (
    DPTForDepthEstimation.from_pretrained(
        MIDAS_MODEL_NAME
    )
    .to(MIDAS_DEVICE)
)

midas_model.eval()

print("Model :", MIDAS_MODEL_NAME)
print("Device:", MIDAS_DEVICE)

# MiDaS 추론 함수
from PIL import Image
import torch.nn.functional as F


def predict_midas_relative_depth(
    image_tensor: torch.Tensor,
    model,
    image_processor,
    device,
) -> np.ndarray:
    """
    [3, H, W] RGB Tensor에서 MiDaS 상대 깊이를 추론합니다.

    반환값
    -------
    np.ndarray
        원본 입력과 동일한 [H, W] 크기의 float32 상대 깊이 배열
    """

    if image_tensor.ndim != 3:
        raise ValueError(
            "image_tensor는 [3, H, W] 형태여야 합니다."
        )

    if image_tensor.shape[0] != 3:
        raise ValueError(
            "RGB 3채널 이미지가 필요합니다."
        )

    height, width = image_tensor.shape[-2:]

    rgb_array = (
        image_tensor
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
    )

    rgb_uint8 = np.clip(
        rgb_array * 255.0,
        0,
        255,
    ).astype(np.uint8)

    pil_image = Image.fromarray(
        rgb_uint8,
        mode="RGB",
    )

    inputs = image_processor(
        images=pil_image,
        return_tensors="pt",
    )

    pixel_values = inputs[
        "pixel_values"
    ].to(device)

    with torch.inference_mode():
        outputs = model(
            pixel_values=pixel_values
        )

        predicted_depth = (
            outputs.predicted_depth
        )

        predicted_depth = F.interpolate(
            predicted_depth.unsqueeze(1),
            size=(height, width),
            mode="bicubic",
            align_corners=False,
        )

    return (
        predicted_depth[
            0,
            0,
        ]
        .detach()
        .cpu()
        .numpy()
        .astype(np.float32)
    )

# 대표 이미지 3장 추론
midas_depth_results = {}


for category, sample_index in (
    REPRESENTATIVE_INDICES.items()
):
    sample = test_dataset[
        sample_index
    ]

    midas_depth = (
        predict_midas_relative_depth(
            image_tensor=sample["image"],
            model=midas_model,
            image_processor=midas_processor,
            device=MIDAS_DEVICE,
        )
    )

    midas_depth_results[
        sample_index
    ] = midas_depth

    print(
        category,
        sample_index,
        midas_depth.shape,
        float(midas_depth.min()),
        float(midas_depth.max()),
        float(midas_depth.mean()),
    )

"""MiDaS 계열 출력은 값이 클수록 가까운 영역으로 나타내는 inverse-depth 성격 -> 같은 방향으로 시각적으로 비교하려면 값을 반전해 사용"""

def invert_and_normalize_relative_depth(
    relative_depth: np.ndarray,
) -> np.ndarray:
    """
    MiDaS inverse-depth 성격의 출력을 반전하고
    0~1 범위로 정규화합니다.

    0에 가까울수록 상대적으로 가까움,
    1에 가까울수록 상대적으로 멂으로 표시합니다.
    """

    relative_depth = np.asarray(
        relative_depth,
        dtype=np.float32,
    )

    finite_mask = np.isfinite(
        relative_depth
    )

    if not finite_mask.any():
        raise ValueError(
            "유효한 MiDaS 출력값이 없습니다."
        )

    minimum = float(
        relative_depth[
            finite_mask
        ].min()
    )

    maximum = float(
        relative_depth[
            finite_mask
        ].max()
    )

    if maximum <= minimum:
        raise ValueError(
            "MiDaS 출력 범위가 유효하지 않습니다."
        )

    normalized_inverse_depth = (
        relative_depth - minimum
    ) / (
        maximum - minimum
    )

    normalized_relative_distance = (
        1.0 - normalized_inverse_depth
    )

    return normalized_relative_distance.astype(
        np.float32
    )

midas_distance_results = {}

for sample_index, midas_depth in (
    midas_depth_results.items()
):
    midas_distance_results[
        sample_index
    ] = (
        invert_and_normalize_relative_depth(
            midas_depth
        )
    )

# MiDaS Heatmap 저장

MIDAS_ROOT = (
    config_utils.OUTPUT_ROOT
    / "relative_depth_comparison"
    / "midas"
)

MIDAS_HEATMAP_ROOT = (
    MIDAS_ROOT
    / "heatmaps"
)

MIDAS_HEATMAP_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in (
    REPRESENTATIVE_INDICES.items()
):
    sample = test_dataset[
        sample_index
    ]

    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
    )

    midas_distance = (
        midas_distance_results[
            sample_index
        ]
    )

    figure, axes = plt.subplots(
        1,
        2,
        figsize=(13, 5),
    )

    axes[0].imshow(
        rgb_image
    )
    axes[0].set_title(
        "RGB Image"
    )
    axes[0].axis("off")

    heatmap_handle = axes[1].imshow(
        midas_distance,
        cmap="inferno",
        vmin=0,
        vmax=1,
    )

    axes[1].set_title(
        "MiDaS Relative Depth"
    )
    axes[1].axis("off")

    colorbar = figure.colorbar(
        heatmap_handle,
        ax=axes[1],
        fraction=0.046,
        pad=0.04,
    )

    colorbar.set_label(
        "Normalized relative distance"
    )

    figure.suptitle(
        (
            f"{category.capitalize()} case "
            f"— Sample {sample_index}"
        )
    )

    figure.tight_layout(
        rect=[0, 0, 1, 0.94]
    )

    save_path = (
        MIDAS_HEATMAP_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_midas_heatmap.png"
        )
    )

    figure.savefig(
        save_path,
        dpi=200,
        bbox_inches="tight",
    )

    np.save(
        MIDAS_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_midas_raw.npy"
        ),
        midas_depth_results[
            sample_index
        ],
    )

    np.save(
        MIDAS_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_midas_normalized.npy"
        ),
        midas_distance,
    )

    plt.show()
    plt.close(figure)

    print("저장 완료:", save_path)

# MiDaS Point Cloud 생성 함수
def relative_depth_to_pseudo_point_cloud(
    relative_distance: np.ndarray,
    rgb: np.ndarray,
    stride: int = 2,
    depth_scale: float = 40.0,
    minimum_depth: float = 1.0,
):
    """
    0~1 상대 거리값으로 pseudo point cloud를 생성합니다.

    relative_distance:
        0에 가까울수록 가까움
        1에 가까울수록 멂

    출력 Z는 시각화를 위한 임의 스케일이며
    실제 미터 단위가 아닙니다.
    """

    if relative_distance.ndim != 2:
        raise ValueError(
            "relative_distance는 [H, W]여야 합니다."
        )

    if (
        rgb.ndim != 3
        or rgb.shape[2] != 3
    ):
        raise ValueError(
            "rgb는 [H, W, 3]이어야 합니다."
        )

    if (
        rgb.shape[:2]
        != relative_distance.shape
    ):
        raise ValueError(
            "RGB와 상대 깊이 해상도가 다릅니다."
        )

    height, width = (
        relative_distance.shape
    )

    focal_length = float(
        max(height, width)
    )

    fx = focal_length
    fy = focal_length
    cx = (width - 1) / 2.0
    cy = (height - 1) / 2.0

    v, u = np.mgrid[
        0:height:stride,
        0:width:stride,
    ]

    sampled_relative = relative_distance[
        0:height:stride,
        0:width:stride,
    ]

    sampled_rgb = rgb[
        0:height:stride,
        0:width:stride,
    ]

    z = (
        minimum_depth
        + sampled_relative
        * depth_scale
    )

    x = (
        (u - cx)
        * z
        / fx
    )

    y = (
        (v - cy)
        * z
        / fy
    )

    points = np.column_stack(
        [
            x.ravel(),
            y.ravel(),
            z.ravel(),
        ]
    ).astype(np.float32)

    colors = (
        sampled_rgb
        .reshape(-1, 3)
        .astype(np.float32)
    )

    return points, colors

# Plotly Point Cloud 저장
def plot_midas_point_cloud(
    points,
    colors,
    title,
    save_html_path=None,
    max_points=40000,
):
    if len(points) > max_points:
        indices = np.linspace(
            0,
            len(points) - 1,
            max_points,
            dtype=np.int64,
        )

        points = points[indices]
        colors = colors[indices]

    plotly_colors = (
        rgb_array_to_plotly_colors(
            colors
        )
    )

    figure = go.Figure(
        data=[
            go.Scatter3d(
                x=points[:, 0],
                y=points[:, 2],
                z=-points[:, 1],
                mode="markers",
                marker={
                    "size": 1.3,
                    "color": plotly_colors,
                    "opacity": 0.9,
                },
                hovertemplate=(
                    "X: %{x:.2f}<br>"
                    "Relative Z: %{y:.2f}<br>"
                    "Y: %{z:.2f}"
                    "<extra></extra>"
                ),
            )
        ]
    )

    figure.update_layout(
        title={
            "text": title,
            "x": 0.5,
            "xanchor": "center",
        },
        scene={
            "xaxis_title": "X",
            "yaxis_title": (
                "Relative depth Z"
            ),
            "zaxis_title": "-Y",
            "aspectmode": "data",
            "camera": {
                "eye": {
                    "x": 0.0,
                    "y": -1.7,
                    "z": 0.6,
                }
            },
        },
        height=750,
        margin={
            "l": 0,
            "r": 0,
            "t": 70,
            "b": 0,
        },
    )

    if save_html_path is not None:
        save_html_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        figure.write_html(
            str(save_html_path),
            include_plotlyjs=True,
            full_html=True,
        )

        print(
            "HTML 저장 완료:",
            save_html_path,
        )

    figure.show()

    return figure

# 대표 사례 생성
MIDAS_POINT_CLOUD_ROOT = (
    MIDAS_ROOT
    / "point_clouds"
)

MIDAS_POINT_CLOUD_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in (
    REPRESENTATIVE_INDICES.items()
):
    sample = test_dataset[
        sample_index
    ]

    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
    )

    relative_distance = (
        midas_distance_results[
            sample_index
        ]
    )

    points, colors = (
        relative_depth_to_pseudo_point_cloud(
            relative_distance=relative_distance,
            rgb=rgb_image,
            stride=2,
            depth_scale=40.0,
            minimum_depth=1.0,
        )
    )

    sample_root = (
        MIDAS_POINT_CLOUD_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
        )
    )

    sample_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    np.save(
        sample_root
        / "midas_points.npy",
        points,
    )

    np.save(
        sample_root
        / "midas_colors.npy",
        colors,
    )

    html_path = (
        sample_root
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_midas_point_cloud.html"
        )
    )

    plot_midas_point_cloud(
        points=points,
        colors=colors,
        title=(
            f"{category.capitalize()} case "
            f"— Sample {sample_index}<br>"
            "MiDaS Relative-depth "
            "Pseudo Point Cloud"
        ),
        save_html_path=html_path,
    )

"""Deep Anything"""

# 기존 baseline과 finetuning도 518*518 크기로(동일한 기준을 위해) 시각화

EVALUATION_ROOT = (
    config_utils.OUTPUT_ROOT
    / "finetuned_evaluation"
)

PREDICTION_DIR = (
    EVALUATION_ROOT
    / "predictions"
)

BASELINE_PREDICTION_DIR = (
    EVALUATION_ROOT
    / "same_condition_comparison"
    / "baseline_predictions"
)

FINAL_COMPARISON_ROOT = (
    config_utils.OUTPUT_ROOT
    / "relative_depth_comparison"
    / "final_comparisons"
)

FINAL_COMPARISON_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in REPRESENTATIVE_INDICES.items():
    sample = test_dataset[sample_index]

    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
        .clip(0.0, 1.0)
    )

    virtual_depth = virtual_depth_results[
        sample_index
    ]

    midas_distance = midas_distance_results[
        sample_index
    ]

    baseline_depth = np.load(
        BASELINE_PREDICTION_DIR
        / f"sample_{sample_index:03d}_pred_baseline.npy"
    ).astype(np.float32)

    finetuned_depth = np.load(
        PREDICTION_DIR
        / f"sample_{sample_index:03d}_pred_finetuned.npy"
    ).astype(np.float32)

    print(
        category,
        "RGB:", rgb_image.shape,
        "Virtual:", virtual_depth.shape,
        "MiDaS:", midas_distance.shape,
        "Before:", baseline_depth.shape,
        "After:", finetuned_depth.shape,
    )

    assert rgb_image.shape[:2] == (518, 518)
    assert virtual_depth.shape == (518, 518)
    assert midas_distance.shape == (518, 518)
    assert baseline_depth.shape == (518, 518)
    assert finetuned_depth.shape == (518, 518)

    figure, axes = plt.subplots(
        1,
        5,
        figsize=(22, 5),
    )

    axes[0].imshow(
        rgb_image,
        aspect="equal",
    )
    axes[0].set_title("RGB")
    axes[0].axis("off")

    virtual_handle = axes[1].imshow(
        virtual_depth,
        cmap="inferno",
        vmin=0,
        vmax=255,
        aspect="equal",
    )
    axes[1].set_title(
        "Virtual Depth\nBrightness-based"
    )
    axes[1].axis("off")

    midas_handle = axes[2].imshow(
        midas_distance,
        cmap="inferno",
        vmin=0,
        vmax=1,
        aspect="equal",
    )
    axes[2].set_title(
        "MiDaS\nRelative distance"
    )
    axes[2].axis("off")

    baseline_handle = axes[3].imshow(
        baseline_depth,
        cmap="inferno",
        vmin=config_utils.MIN_DEPTH,
        vmax=config_utils.MAX_DEPTH,
        aspect="equal",
    )
    axes[3].set_title(
        "DA V2 Before\nMetric depth"
    )
    axes[3].axis("off")

    finetuned_handle = axes[4].imshow(
        finetuned_depth,
        cmap="inferno",
        vmin=config_utils.MIN_DEPTH,
        vmax=config_utils.MAX_DEPTH,
        aspect="equal",
    )
    axes[4].set_title(
        "DA V2 After\nMetric depth"
    )
    axes[4].axis("off")

    # 값의 의미가 다르므로 컬러바를 분리
    figure.colorbar(
        virtual_handle,
        ax=axes[1],
        fraction=0.046,
        pad=0.04,
        label="Brightness value",
    )

    figure.colorbar(
        midas_handle,
        ax=axes[2],
        fraction=0.046,
        pad=0.04,
        label="Normalized relative distance",
    )

    # Before/After는 동일한 단위·범위이므로 공통 컬러바
    figure.colorbar(
        finetuned_handle,
        ax=[axes[3], axes[4]],
        fraction=0.025,
        pad=0.02,
        label="Depth (m)",
    )

    figure.suptitle(
        (
            f"{category.capitalize()} case "
            f"— Sample {sample_index} "
            "(all results: 518×518)"
        ),
        fontsize=15,
    )

    figure.subplots_adjust(
        left=0.02,
        right=0.96,
        top=0.84,
        bottom=0.08,
        wspace=0.28,
    )

    save_path = (
        FINAL_COMPARISON_ROOT
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_all_methods_518.png"
        )
    )

    figure.savefig(
        save_path,
        dpi=250,
        bbox_inches="tight",
    )

    plt.show()
    plt.close(figure)

    print("저장 완료:", save_path)

print("Baseline prediction shape:",
      np.load(
          BASELINE_PREDICTION_DIR
          / "sample_083_pred_baseline.npy"
      ).shape)

print("Fine-tuned prediction shape:",
      np.load(
          PREDICTION_DIR
          / "sample_083_pred_finetuned.npy"
      ).shape)

# Point Cloud 변환 함수

def metric_depth_to_pseudo_point_cloud(
    depth: np.ndarray,
    rgb: np.ndarray,
    min_depth: float = 0.1,
    max_depth: float = 80.0,
    stride: int = 2,
    focal_length: float | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Metric depth map을 근사 카메라 내부 파라미터로
    pseudo point cloud로 변환합니다.

    주의:
    calibration 파일이 없으므로 정밀한 3D 복원은 아닙니다.
    Z값 자체는 모델이 예측한 metric depth(m)를 사용합니다.
    """

    depth = np.asarray(depth, dtype=np.float32)
    rgb = np.asarray(rgb, dtype=np.float32)

    if depth.ndim != 2:
        raise ValueError(
            f"depth는 [H, W]여야 합니다. 입력: {depth.shape}"
        )

    if rgb.ndim != 3 or rgb.shape[2] != 3:
        raise ValueError(
            f"rgb는 [H, W, 3]이어야 합니다. 입력: {rgb.shape}"
        )

    if rgb.shape[:2] != depth.shape:
        raise ValueError(
            "RGB와 depth 해상도가 일치하지 않습니다."
        )

    height, width = depth.shape

    if focal_length is None:
        focal_length = float(max(height, width))

    fx = focal_length
    fy = focal_length
    cx = (width - 1) / 2.0
    cy = (height - 1) / 2.0

    v, u = np.mgrid[
        0:height:stride,
        0:width:stride,
    ]

    sampled_depth = depth[
        0:height:stride,
        0:width:stride,
    ]

    sampled_rgb = rgb[
        0:height:stride,
        0:width:stride,
    ]

    valid = (
        np.isfinite(sampled_depth)
        & (sampled_depth >= min_depth)
        & (sampled_depth <= max_depth)
    )

    z = sampled_depth[valid]

    x = (
        (u[valid] - cx)
        * z
        / fx
    )

    y = (
        (v[valid] - cy)
        * z
        / fy
    )

    points = np.stack(
        [x, y, z],
        axis=1,
    ).astype(np.float32)

    colors = sampled_rgb[
        valid
    ].astype(np.float32)

    colors = np.clip(
        colors,
        0.0,
        1.0,
    )

    return points, colors

# Before/After 비교 Plotly 함수
from plotly.subplots import make_subplots


def compare_metric_point_clouds(
    baseline_points: np.ndarray,
    baseline_colors: np.ndarray,
    finetuned_points: np.ndarray,
    finetuned_colors: np.ndarray,
    title: str,
    save_html_path=None,
    max_points: int = 40000,
    marker_size: float = 1.2,
):
    """
    DA V2 Before/After Point Cloud를
    동일한 Plotly 조건으로 비교합니다.
    """

    def subsample(points, colors):
        if len(points) <= max_points:
            return points, colors

        indices = np.linspace(
            0,
            len(points) - 1,
            max_points,
            dtype=np.int64,
        )

        return points[indices], colors[indices]

    baseline_points, baseline_colors = subsample(
        baseline_points,
        baseline_colors,
    )

    finetuned_points, finetuned_colors = subsample(
        finetuned_points,
        finetuned_colors,
    )

    baseline_plotly_colors = (
        rgb_array_to_plotly_colors(
            baseline_colors
        )
    )

    finetuned_plotly_colors = (
        rgb_array_to_plotly_colors(
            finetuned_colors
        )
    )

    figure = make_subplots(
        rows=1,
        cols=2,
        specs=[
            [
                {"type": "scene"},
                {"type": "scene"},
            ]
        ],
        subplot_titles=[
            "DA V2 Before",
            "DA V2 After",
        ],
        horizontal_spacing=0.03,
    )

    figure.add_trace(
        go.Scatter3d(
            x=baseline_points[:, 0],
            y=baseline_points[:, 2],
            z=-baseline_points[:, 1],
            mode="markers",
            marker={
                "size": marker_size,
                "color": baseline_plotly_colors,
                "opacity": 0.9,
            },
            name="DA V2 Before",
            hovertemplate=(
                "X: %{x:.2f}<br>"
                "Depth Z: %{y:.2f} m<br>"
                "Y: %{z:.2f}"
                "<extra>Before</extra>"
            ),
        ),
        row=1,
        col=1,
    )

    figure.add_trace(
        go.Scatter3d(
            x=finetuned_points[:, 0],
            y=finetuned_points[:, 2],
            z=-finetuned_points[:, 1],
            mode="markers",
            marker={
                "size": marker_size,
                "color": finetuned_plotly_colors,
                "opacity": 0.9,
            },
            name="DA V2 After",
            hovertemplate=(
                "X: %{x:.2f}<br>"
                "Depth Z: %{y:.2f} m<br>"
                "Y: %{z:.2f}"
                "<extra>After</extra>"
            ),
        ),
        row=1,
        col=2,
    )

    common_scene = {
        "xaxis_title": "X",
        "yaxis_title": "Depth Z (m)",
        "zaxis_title": "-Y",
        "aspectmode": "data",
        "camera": {
            "eye": {
                "x": 0.0,
                "y": -1.7,
                "z": 0.6,
            }
        },
    }

    figure.update_layout(
        title={
            "text": title,
            "x": 0.5,
            "xanchor": "center",
        },
        scene=common_scene,
        scene2=common_scene,
        height=700,
        width=1300,
        showlegend=False,
        margin={
            "l": 0,
            "r": 0,
            "t": 80,
            "b": 0,
        },
    )

    if save_html_path is not None:
        save_html_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        figure.write_html(
            str(save_html_path),
            include_plotlyjs=True,
            full_html=True,
        )

        print("HTML 저장 완료:", save_html_path)

    figure.show()

    return figure

# 대표 사례 3개 생성 및 저장

DA_POINT_CLOUD_ROOT = (
    config_utils.OUTPUT_ROOT
    / "relative_depth_comparison"
    / "depth_anything_v2"
    / "point_clouds"
)

DA_POINT_CLOUD_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


for category, sample_index in REPRESENTATIVE_INDICES.items():
    sample = test_dataset[sample_index]

    rgb_image = (
        sample["image"]
        .detach()
        .cpu()
        .permute(1, 2, 0)
        .numpy()
        .astype(np.float32)
        .clip(0.0, 1.0)
    )

    baseline_depth = np.load(
        BASELINE_PREDICTION_DIR
        / f"sample_{sample_index:03d}_pred_baseline.npy"
    ).astype(np.float32)

    finetuned_depth = np.load(
        PREDICTION_DIR
        / f"sample_{sample_index:03d}_pred_finetuned.npy"
    ).astype(np.float32)

    if baseline_depth.shape != (518, 518):
        raise ValueError(
            f"Baseline 크기 오류: {baseline_depth.shape}"
        )

    if finetuned_depth.shape != (518, 518):
        raise ValueError(
            f"Fine-tuned 크기 오류: {finetuned_depth.shape}"
        )

    baseline_points, baseline_colors = (
        metric_depth_to_pseudo_point_cloud(
            depth=baseline_depth,
            rgb=rgb_image,
            min_depth=config_utils.MIN_DEPTH,
            max_depth=config_utils.MAX_DEPTH,
            stride=2,
        )
    )

    finetuned_points, finetuned_colors = (
        metric_depth_to_pseudo_point_cloud(
            depth=finetuned_depth,
            rgb=rgb_image,
            min_depth=config_utils.MIN_DEPTH,
            max_depth=config_utils.MAX_DEPTH,
            stride=2,
        )
    )

    sample_root = (
        DA_POINT_CLOUD_ROOT
        / f"{category}_sample_{sample_index:03d}"
    )

    sample_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    np.save(
        sample_root / "baseline_points.npy",
        baseline_points,
    )

    np.save(
        sample_root / "baseline_colors.npy",
        baseline_colors,
    )

    np.save(
        sample_root / "finetuned_points.npy",
        finetuned_points,
    )

    np.save(
        sample_root / "finetuned_colors.npy",
        finetuned_colors,
    )

    html_path = (
        sample_root
        / (
            f"{category}_sample_"
            f"{sample_index:03d}"
            "_da_v2_before_vs_after.html"
        )
    )

    compare_metric_point_clouds(
        baseline_points=baseline_points,
        baseline_colors=baseline_colors,
        finetuned_points=finetuned_points,
        finetuned_colors=finetuned_colors,
        title=(
            f"{category.capitalize()} case "
            f"— Sample {sample_index}<br>"
            "DA V2 Metric-depth Pseudo Point Cloud"
        ),
        save_html_path=html_path,
        max_points=40000,
        marker_size=1.2,
    )

    print(
        f"완료: {category}, sample {sample_index}"
    )

