# -*- coding: utf-8 -*-
"""05_streamlit_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3bD_bU7qfMEegef-bVFYgetyteOzdn7
"""

from google.colab import drive

drive.mount(
    "/content/drive",
    force_remount=False,
)

from pathlib import Path
import sys


PROJECT_ROOT = Path(
    "/content/drive/MyDrive/2026/comento/week4"
)

STREAMLIT_ROOT = (
    PROJECT_ROOT
    / "streamlit_app"
)

APP_PATH = (
    STREAMLIT_ROOT
    / "app.py"
)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )

if str(STREAMLIT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(STREAMLIT_ROOT),
    )


print("PROJECT_ROOT   :", PROJECT_ROOT)
print("STREAMLIT_ROOT :", STREAMLIT_ROOT)
print("APP_PATH       :", APP_PATH)

print("Project exists :", PROJECT_ROOT.exists())
print("App exists     :", APP_PATH.exists())

!pip install -q \
    streamlit \
    ultralytics \
    transformers

import streamlit
import ultralytics
import transformers

print("Streamlit   :", streamlit.__version__)
print("Ultralytics :", ultralytics.__version__)
print("Transformers:", transformers.__version__)

import importlib

import config as app_config

importlib.reload(
    app_config
)


required_paths = {
    "Streamlit app": APP_PATH,
    "Depth checkpoint": (
        app_config.CHECKPOINT_PATH
    ),
    "YOLO checkpoint": (
        app_config.YOLO_CHECKPOINT_PATH
    ),
}


all_files_exist = True

for name, path in required_paths.items():
    exists = path.exists()

    print(
        f"{name:20s}: "
        f"{exists} | {path}"
    )

    if not exists:
        all_files_exist = False


if not all_files_exist:
    raise FileNotFoundError(
        "필수 파일 중 존재하지 않는 파일이 있습니다."
    )

print("\n필수 파일 확인 완료")

import py_compile


python_files = [
    STREAMLIT_ROOT / "app.py",
    STREAMLIT_ROOT / "config.py",
    STREAMLIT_ROOT / "model_loader.py",
    STREAMLIT_ROOT / "inference.py",
    STREAMLIT_ROOT / "visualization.py",
]


for path in python_files:
    py_compile.compile(
        str(path),
        doraise=True,
    )

    print(
        "문법 검사 성공:",
        path.name,
    )

# 기존 streamlit 서버 종료
!pkill -9 -f "streamlit run" || true
!fuser -k 8501/tcp || true

import time

time.sleep(2)

print("기존 Streamlit 서버 정리 완료")

# streamlit 서버 시작
!rm -f /content/streamlit.log

!nohup streamlit run "$APP_PATH" \
    --server.port=8501 \
    --server.address=0.0.0.0 \
    --server.headless=true \
    --server.enableCORS=false \
    --server.enableXsrfProtection=false \
    --server.enableWebsocketCompression=false \
    --browser.gatherUsageStats=false \
    > /content/streamlit.log 2>&1 &

print("Streamlit 서버 시작 명령 실행 완료")

import time
import requests


HEALTH_URL = (
    "http://127.0.0.1:8501/"
    "_stcore/health"
)

server_ready = False


for attempt in range(30):
    try:
        response = requests.get(
            HEALTH_URL,
            timeout=2,
        )

        if response.status_code == 200:
            server_ready = True

            print(
                f"서버 준비 완료 "
                f"({attempt + 1}번째 확인)"
            )

            print(
                "Response:",
                response.text,
            )

            break

    except requests.RequestException:
        pass

    print(
        f"서버 준비 대기 중: "
        f"{attempt + 1}/30"
    )

    time.sleep(2)


print("\nServer ready:", server_ready)


if not server_ready:
    raise RuntimeError(
        "Streamlit 서버가 준비되지 않았습니다. "
        "다음 로그 확인 셀을 실행하세요."
    )

# streamlit 화면 열기
from google.colab import output


output.serve_kernel_port_as_iframe(
    8501,
    height=1100,
)

# 오류 로그 확인
!tail -n 200 /content/streamlit.log

# 서버 프로세스 확인
!ps aux | grep "[s]treamlit"

# 포트 상태 확인
!ss -ltnp | grep 8501 || true

# streamlit 서버 종료
!pkill -9 -f "streamlit run" || true
!fuser -k 8501/tcp || true

print("Streamlit 서버 종료 완료")

